/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from "../programs";

/** UnauthorizedSender: Unauthorized sender. */
export const POLICY_CHALLENGES_ERROR__UNAUTHORIZED_SENDER = 0x1770; // 6000
/** UnauthorizedAdmin: Unauthorized admin. */
export const POLICY_CHALLENGES_ERROR__UNAUTHORIZED_ADMIN = 0x1771; // 6001
/** ChallengeNotActive: Challenge is not active. */
export const POLICY_CHALLENGES_ERROR__CHALLENGE_NOT_ACTIVE = 0x1772; // 6002
/** ChallengeFull: Challenge is full. */
export const POLICY_CHALLENGES_ERROR__CHALLENGE_FULL = 0x1773; // 6003
/** AlreadyParticipating: Already participating in challenge. */
export const POLICY_CHALLENGES_ERROR__ALREADY_PARTICIPATING = 0x1774; // 6004
/** InvalidTimeRange: Invalid time range. */
export const POLICY_CHALLENGES_ERROR__INVALID_TIME_RANGE = 0x1775; // 6005
/** InvalidMaxParticipants: Invalid max participants. */
export const POLICY_CHALLENGES_ERROR__INVALID_MAX_PARTICIPANTS = 0x1776; // 6006
/** InvalidEntranceCost: Invalid entrance cost. */
export const POLICY_CHALLENGES_ERROR__INVALID_ENTRANCE_COST = 0x1777; // 6007
/** InvalidMinimumTradingDays: Invalid minimum trading days. */
export const POLICY_CHALLENGES_ERROR__INVALID_MINIMUM_TRADING_DAYS = 0x1778; // 6008
/** InvalidDailyDrawdown: Invalid daily drawdown. */
export const POLICY_CHALLENGES_ERROR__INVALID_DAILY_DRAWDOWN = 0x1779; // 6009
/** InvalidMaximumLoss: Invalid maximum loss. */
export const POLICY_CHALLENGES_ERROR__INVALID_MAXIMUM_LOSS = 0x177a; // 6010
/** InvalidProfitTarget: Invalid profit target. */
export const POLICY_CHALLENGES_ERROR__INVALID_PROFIT_TARGET = 0x177b; // 6011
/** InvalidParticipantIndex: Invalid participant index. */
export const POLICY_CHALLENGES_ERROR__INVALID_PARTICIPANT_INDEX = 0x177c; // 6012
/** InvalidChallengeId: Invalid challenge ID. */
export const POLICY_CHALLENGES_ERROR__INVALID_CHALLENGE_ID = 0x177d; // 6013

export type PolicyChallengesError =
  | typeof POLICY_CHALLENGES_ERROR__ALREADY_PARTICIPATING
  | typeof POLICY_CHALLENGES_ERROR__CHALLENGE_FULL
  | typeof POLICY_CHALLENGES_ERROR__CHALLENGE_NOT_ACTIVE
  | typeof POLICY_CHALLENGES_ERROR__INVALID_CHALLENGE_ID
  | typeof POLICY_CHALLENGES_ERROR__INVALID_DAILY_DRAWDOWN
  | typeof POLICY_CHALLENGES_ERROR__INVALID_ENTRANCE_COST
  | typeof POLICY_CHALLENGES_ERROR__INVALID_MAXIMUM_LOSS
  | typeof POLICY_CHALLENGES_ERROR__INVALID_MAX_PARTICIPANTS
  | typeof POLICY_CHALLENGES_ERROR__INVALID_MINIMUM_TRADING_DAYS
  | typeof POLICY_CHALLENGES_ERROR__INVALID_PARTICIPANT_INDEX
  | typeof POLICY_CHALLENGES_ERROR__INVALID_PROFIT_TARGET
  | typeof POLICY_CHALLENGES_ERROR__INVALID_TIME_RANGE
  | typeof POLICY_CHALLENGES_ERROR__UNAUTHORIZED_ADMIN
  | typeof POLICY_CHALLENGES_ERROR__UNAUTHORIZED_SENDER;

let policyChallengesErrorMessages:
  | Record<PolicyChallengesError, string>
  | undefined;
if (process.env.NODE_ENV !== "production") {
  policyChallengesErrorMessages = {
    [POLICY_CHALLENGES_ERROR__ALREADY_PARTICIPATING]: `Already participating in challenge.`,
    [POLICY_CHALLENGES_ERROR__CHALLENGE_FULL]: `Challenge is full.`,
    [POLICY_CHALLENGES_ERROR__CHALLENGE_NOT_ACTIVE]: `Challenge is not active.`,
    [POLICY_CHALLENGES_ERROR__INVALID_CHALLENGE_ID]: `Invalid challenge ID.`,
    [POLICY_CHALLENGES_ERROR__INVALID_DAILY_DRAWDOWN]: `Invalid daily drawdown.`,
    [POLICY_CHALLENGES_ERROR__INVALID_ENTRANCE_COST]: `Invalid entrance cost.`,
    [POLICY_CHALLENGES_ERROR__INVALID_MAXIMUM_LOSS]: `Invalid maximum loss.`,
    [POLICY_CHALLENGES_ERROR__INVALID_MAX_PARTICIPANTS]: `Invalid max participants.`,
    [POLICY_CHALLENGES_ERROR__INVALID_MINIMUM_TRADING_DAYS]: `Invalid minimum trading days.`,
    [POLICY_CHALLENGES_ERROR__INVALID_PARTICIPANT_INDEX]: `Invalid participant index.`,
    [POLICY_CHALLENGES_ERROR__INVALID_PROFIT_TARGET]: `Invalid profit target.`,
    [POLICY_CHALLENGES_ERROR__INVALID_TIME_RANGE]: `Invalid time range.`,
    [POLICY_CHALLENGES_ERROR__UNAUTHORIZED_ADMIN]: `Unauthorized admin.`,
    [POLICY_CHALLENGES_ERROR__UNAUTHORIZED_SENDER]: `Unauthorized sender.`,
  };
}

export function getPolicyChallengesErrorMessage(
  code: PolicyChallengesError,
): string {
  if (process.env.NODE_ENV !== "production") {
    return (
      policyChallengesErrorMessages as Record<PolicyChallengesError, string>
    )[code];
  }

  return "Error message not available in production bundles.";
}

export function isPolicyChallengesError<
  TProgramErrorCode extends PolicyChallengesError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    POLICY_CHALLENGES_PROGRAM_ADDRESS,
    code,
  );
}
