/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum ValidateOperation {
  Creation,
  Execution,
  UseFunds,
  ReturnFunds,
  Report,
}

export type ValidateOperationArgs = ValidateOperation;

export function getValidateOperationEncoder(): FixedSizeEncoder<ValidateOperationArgs> {
  return getEnumEncoder(ValidateOperation);
}

export function getValidateOperationDecoder(): FixedSizeDecoder<ValidateOperation> {
  return getEnumDecoder(ValidateOperation);
}

export function getValidateOperationCodec(): FixedSizeCodec<
  ValidateOperationArgs,
  ValidateOperation
> {
  return combineCodec(
    getValidateOperationEncoder(),
    getValidateOperationDecoder()
  );
}
