/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { FEE_COLLECTION_TIME_BASED_PROGRAM_ADDRESS } from '../programs';

/** InvalidConfig: Invalid fee configuration */
export const FEE_COLLECTION_TIME_BASED_ERROR__INVALID_CONFIG = 0x1770; // 6000
/** InvalidPeriod: Invalid time period */
export const FEE_COLLECTION_TIME_BASED_ERROR__INVALID_PERIOD = 0x1771; // 6001

export type FeeCollectionTimeBasedError =
  | typeof FEE_COLLECTION_TIME_BASED_ERROR__INVALID_CONFIG
  | typeof FEE_COLLECTION_TIME_BASED_ERROR__INVALID_PERIOD;

let feeCollectionTimeBasedErrorMessages:
  | Record<FeeCollectionTimeBasedError, string>
  | undefined;
if (process.env.NODE_ENV !== 'production') {
  feeCollectionTimeBasedErrorMessages = {
    [FEE_COLLECTION_TIME_BASED_ERROR__INVALID_CONFIG]: `Invalid fee configuration`,
    [FEE_COLLECTION_TIME_BASED_ERROR__INVALID_PERIOD]: `Invalid time period`,
  };
}

export function getFeeCollectionTimeBasedErrorMessage(
  code: FeeCollectionTimeBasedError
): string {
  if (process.env.NODE_ENV !== 'production') {
    return (
      feeCollectionTimeBasedErrorMessages as Record<
        FeeCollectionTimeBasedError,
        string
      >
    )[code];
  }

  return 'Error message not available in production bundles.';
}

export function isFeeCollectionTimeBasedError<
  TProgramErrorCode extends FeeCollectionTimeBasedError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    FEE_COLLECTION_TIME_BASED_PROGRAM_ADDRESS,
    code
  );
}
