/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getFeeAmountsDecoder,
  getFeeAmountsEncoder,
  getFeeRecipientsDecoder,
  getFeeRecipientsEncoder,
  type FeeAmounts,
  type FeeAmountsArgs,
  type FeeRecipients,
  type FeeRecipientsArgs,
} from "../types";

export const VAULT_FEES_DISCRIMINATOR = new Uint8Array([
  160, 42, 52, 120, 52, 123, 127, 118,
]);

export function getVaultFeesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(VAULT_FEES_DISCRIMINATOR);
}

export type VaultFees = {
  discriminator: ReadonlyUint8Array;
  /** The vault this fee account belongs to */
  vault: Address;
  /** External program that calculates fees (fractions, time-based, all-in-one) */
  feeCalcProgram: Address;
  /** Verified recipients for each fee type */
  recipients: FeeRecipients;
  /** Unclaimed fees (accumulated from calculations) */
  unclaimed: FeeAmounts;
  /** Total fees collected over lifetime */
  totalCollected: FeeAmounts;
  /** Total fees claimed over lifetime */
  totalClaimed: FeeAmounts;
  /** High water mark for performance fees */
  highWaterMark: bigint;
  /** Last fee calculation timestamp */
  lastUpdate: bigint;
  /** Bump seed for PDA */
  bump: number;
};

export type VaultFeesArgs = {
  /** The vault this fee account belongs to */
  vault: Address;
  /** External program that calculates fees (fractions, time-based, all-in-one) */
  feeCalcProgram: Address;
  /** Verified recipients for each fee type */
  recipients: FeeRecipientsArgs;
  /** Unclaimed fees (accumulated from calculations) */
  unclaimed: FeeAmountsArgs;
  /** Total fees collected over lifetime */
  totalCollected: FeeAmountsArgs;
  /** Total fees claimed over lifetime */
  totalClaimed: FeeAmountsArgs;
  /** High water mark for performance fees */
  highWaterMark: number | bigint;
  /** Last fee calculation timestamp */
  lastUpdate: number | bigint;
  /** Bump seed for PDA */
  bump: number;
};

/** Gets the encoder for {@link VaultFeesArgs} account data. */
export function getVaultFeesEncoder(): FixedSizeEncoder<VaultFeesArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["vault", getAddressEncoder()],
      ["feeCalcProgram", getAddressEncoder()],
      ["recipients", getFeeRecipientsEncoder()],
      ["unclaimed", getFeeAmountsEncoder()],
      ["totalCollected", getFeeAmountsEncoder()],
      ["totalClaimed", getFeeAmountsEncoder()],
      ["highWaterMark", getU64Encoder()],
      ["lastUpdate", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VAULT_FEES_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link VaultFees} account data. */
export function getVaultFeesDecoder(): FixedSizeDecoder<VaultFees> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["vault", getAddressDecoder()],
    ["feeCalcProgram", getAddressDecoder()],
    ["recipients", getFeeRecipientsDecoder()],
    ["unclaimed", getFeeAmountsDecoder()],
    ["totalCollected", getFeeAmountsDecoder()],
    ["totalClaimed", getFeeAmountsDecoder()],
    ["highWaterMark", getU64Decoder()],
    ["lastUpdate", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link VaultFees} account data. */
export function getVaultFeesCodec(): FixedSizeCodec<VaultFeesArgs, VaultFees> {
  return combineCodec(getVaultFeesEncoder(), getVaultFeesDecoder());
}

export function decodeVaultFees<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<VaultFees, TAddress>;
export function decodeVaultFees<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<VaultFees, TAddress>;
export function decodeVaultFees<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<VaultFees, TAddress> | MaybeAccount<VaultFees, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVaultFeesDecoder(),
  );
}

export async function fetchVaultFees<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<VaultFees, TAddress>> {
  const maybeAccount = await fetchMaybeVaultFees(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVaultFees<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<VaultFees, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVaultFees(maybeAccount);
}

export async function fetchAllVaultFees(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<VaultFees>[]> {
  const maybeAccounts = await fetchAllMaybeVaultFees(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVaultFees(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<VaultFees>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeVaultFees(maybeAccount));
}

export function getVaultFeesSize(): number {
  return 313;
}
