/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INITIALIZE_LIMIT_TRANSFER_DISCRIMINATOR = new Uint8Array([
  231, 140, 57, 76, 17, 243, 161, 149,
]);

export function getInitializeLimitTransferDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_LIMIT_TRANSFER_DISCRIMINATOR,
  );
}

export type InitializeLimitTransferInstruction<
  TProgram extends string = typeof POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPolicyAccount extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountPolicyAccount extends string
        ? WritableAccount<TAccountPolicyAccount>
        : TAccountPolicyAccount,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeLimitTransferInstructionData = {
  discriminator: ReadonlyUint8Array;
  min: bigint;
  max: bigint;
};

export type InitializeLimitTransferInstructionDataArgs = {
  min: number | bigint;
  max: number | bigint;
};

export function getInitializeLimitTransferInstructionDataEncoder(): FixedSizeEncoder<InitializeLimitTransferInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["min", getU64Encoder()],
      ["max", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_LIMIT_TRANSFER_DISCRIMINATOR,
    }),
  );
}

export function getInitializeLimitTransferInstructionDataDecoder(): FixedSizeDecoder<InitializeLimitTransferInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["min", getU64Decoder()],
    ["max", getU64Decoder()],
  ]);
}

export function getInitializeLimitTransferInstructionDataCodec(): FixedSizeCodec<
  InitializeLimitTransferInstructionDataArgs,
  InitializeLimitTransferInstructionData
> {
  return combineCodec(
    getInitializeLimitTransferInstructionDataEncoder(),
    getInitializeLimitTransferInstructionDataDecoder(),
  );
}

export type InitializeLimitTransferAsyncInput<
  TAccountVault extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  policyAccount?: Address<TAccountPolicyAccount>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  min: InitializeLimitTransferInstructionDataArgs["min"];
  max: InitializeLimitTransferInstructionDataArgs["max"];
};

export async function getInitializeLimitTransferInstructionAsync<
  TAccountVault extends string,
  TAccountPolicyAccount extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS,
>(
  input: InitializeLimitTransferAsyncInput<
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeLimitTransferInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.policyAccount.value) {
    accounts.policyAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getAddressEncoder().encode(expectAddress(accounts.vault.value))],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeLimitTransferInstructionDataEncoder().encode(
      args as InitializeLimitTransferInstructionDataArgs,
    ),
    programAddress,
  } as InitializeLimitTransferInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type InitializeLimitTransferInput<
  TAccountVault extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  policyAccount: Address<TAccountPolicyAccount>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  min: InitializeLimitTransferInstructionDataArgs["min"];
  max: InitializeLimitTransferInstructionDataArgs["max"];
};

export function getInitializeLimitTransferInstruction<
  TAccountVault extends string,
  TAccountPolicyAccount extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS,
>(
  input: InitializeLimitTransferInput<
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeLimitTransferInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountPolicyAccount,
  TAccountSigner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeLimitTransferInstructionDataEncoder().encode(
      args as InitializeLimitTransferInstructionDataArgs,
    ),
    programAddress,
  } as InitializeLimitTransferInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeLimitTransferInstruction<
  TProgram extends string = typeof POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    policyAccount: TAccountMetas[1];
    signer: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeLimitTransferInstructionData;
};

export function parseInitializeLimitTransferInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeLimitTransferInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      policyAccount: getNextAccount(),
      signer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeLimitTransferInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
