/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLAIM_PAYOUT_DISCRIMINATOR = new Uint8Array([
  127, 240, 132, 62, 227, 198, 146, 133,
]);

export function getClaimPayoutDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_PAYOUT_DISCRIMINATOR
  );
}

export type ClaimPayoutInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeAccount extends string | AccountMeta<string> = string,
  TAccountParticipant extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeAccount extends string
        ? WritableAccount<TAccountChallengeAccount>
        : TAccountChallengeAccount,
      TAccountParticipant extends string
        ? WritableSignerAccount<TAccountParticipant> &
            AccountSignerMeta<TAccountParticipant>
        : TAccountParticipant,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimPayoutInstructionData = { discriminator: ReadonlyUint8Array };

export type ClaimPayoutInstructionDataArgs = {};

export function getClaimPayoutInstructionDataEncoder(): FixedSizeEncoder<ClaimPayoutInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_PAYOUT_DISCRIMINATOR })
  );
}

export function getClaimPayoutInstructionDataDecoder(): FixedSizeDecoder<ClaimPayoutInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimPayoutInstructionDataCodec(): FixedSizeCodec<
  ClaimPayoutInstructionDataArgs,
  ClaimPayoutInstructionData
> {
  return combineCodec(
    getClaimPayoutInstructionDataEncoder(),
    getClaimPayoutInstructionDataDecoder()
  );
}

export type ClaimPayoutInput<
  TAccountChallengeAccount extends string = string,
  TAccountParticipant extends string = string,
> = {
  challengeAccount: Address<TAccountChallengeAccount>;
  participant: TransactionSigner<TAccountParticipant>;
};

export function getClaimPayoutInstruction<
  TAccountChallengeAccount extends string,
  TAccountParticipant extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: ClaimPayoutInput<TAccountChallengeAccount, TAccountParticipant>,
  config?: { programAddress?: TProgramAddress }
): ClaimPayoutInstruction<
  TProgramAddress,
  TAccountChallengeAccount,
  TAccountParticipant
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeAccount: {
      value: input.challengeAccount ?? null,
      isWritable: true,
    },
    participant: { value: input.participant ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.challengeAccount),
      getAccountMeta(accounts.participant),
    ],
    data: getClaimPayoutInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimPayoutInstruction<
    TProgramAddress,
    TAccountChallengeAccount,
    TAccountParticipant
  >);
}

export type ParsedClaimPayoutInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeAccount: TAccountMetas[0];
    participant: TAccountMetas[1];
  };
  data: ClaimPayoutInstructionData;
};

export function parseClaimPayoutInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimPayoutInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeAccount: getNextAccount(),
      participant: getNextAccount(),
    },
    data: getClaimPayoutInstructionDataDecoder().decode(instruction.data),
  };
}
