/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getPercentDecoder,
  getPercentEncoder,
  type Percent,
  type PercentArgs,
} from "../types";

export const UPDATE_CHALLENGE_TEMPLATE_MAXIMUM_LOSS_DISCRIMINATOR =
  new Uint8Array([111, 239, 61, 167, 113, 215, 92, 38]);

export function getUpdateChallengeTemplateMaximumLossDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CHALLENGE_TEMPLATE_MAXIMUM_LOSS_DISCRIMINATOR,
  );
}

export type UpdateChallengeTemplateMaximumLossInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeTemplateAccount extends string | AccountMeta<string> =
    string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeTemplateAccount extends string
        ? WritableAccount<TAccountChallengeTemplateAccount>
        : TAccountChallengeTemplateAccount,
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateChallengeTemplateMaximumLossInstructionData = {
  discriminator: ReadonlyUint8Array;
  maximumLoss: Percent;
};

export type UpdateChallengeTemplateMaximumLossInstructionDataArgs = {
  maximumLoss: PercentArgs;
};

export function getUpdateChallengeTemplateMaximumLossInstructionDataEncoder(): FixedSizeEncoder<UpdateChallengeTemplateMaximumLossInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["maximumLoss", getPercentEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_CHALLENGE_TEMPLATE_MAXIMUM_LOSS_DISCRIMINATOR,
    }),
  );
}

export function getUpdateChallengeTemplateMaximumLossInstructionDataDecoder(): FixedSizeDecoder<UpdateChallengeTemplateMaximumLossInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["maximumLoss", getPercentDecoder()],
  ]);
}

export function getUpdateChallengeTemplateMaximumLossInstructionDataCodec(): FixedSizeCodec<
  UpdateChallengeTemplateMaximumLossInstructionDataArgs,
  UpdateChallengeTemplateMaximumLossInstructionData
> {
  return combineCodec(
    getUpdateChallengeTemplateMaximumLossInstructionDataEncoder(),
    getUpdateChallengeTemplateMaximumLossInstructionDataDecoder(),
  );
}

export type UpdateChallengeTemplateMaximumLossInput<
  TAccountChallengeTemplateAccount extends string = string,
  TAccountSigner extends string = string,
> = {
  challengeTemplateAccount: Address<TAccountChallengeTemplateAccount>;
  signer: TransactionSigner<TAccountSigner>;
  maximumLoss: UpdateChallengeTemplateMaximumLossInstructionDataArgs["maximumLoss"];
};

export function getUpdateChallengeTemplateMaximumLossInstruction<
  TAccountChallengeTemplateAccount extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: UpdateChallengeTemplateMaximumLossInput<
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateChallengeTemplateMaximumLossInstruction<
  TProgramAddress,
  TAccountChallengeTemplateAccount,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeTemplateAccount: {
      value: input.challengeTemplateAccount ?? null,
      isWritable: true,
    },
    signer: { value: input.signer ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.challengeTemplateAccount),
      getAccountMeta(accounts.signer),
    ],
    data: getUpdateChallengeTemplateMaximumLossInstructionDataEncoder().encode(
      args as UpdateChallengeTemplateMaximumLossInstructionDataArgs,
    ),
    programAddress,
  } as UpdateChallengeTemplateMaximumLossInstruction<
    TProgramAddress,
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >);
}

export type ParsedUpdateChallengeTemplateMaximumLossInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeTemplateAccount: TAccountMetas[0];
    signer: TAccountMetas[1];
  };
  data: UpdateChallengeTemplateMaximumLossInstructionData;
};

export function parseUpdateChallengeTemplateMaximumLossInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateChallengeTemplateMaximumLossInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeTemplateAccount: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getUpdateChallengeTemplateMaximumLossInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
