/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_COST_DISCRIMINATOR =
  new Uint8Array([7, 181, 39, 15, 22, 133, 159, 130]);

export function getUpdateChallengeTemplateEntranceCostDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_COST_DISCRIMINATOR
  );
}

export type UpdateChallengeTemplateEntranceCostInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeTemplateAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeTemplateAccount extends string
        ? WritableAccount<TAccountChallengeTemplateAccount>
        : TAccountChallengeTemplateAccount,
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateChallengeTemplateEntranceCostInstructionData = {
  discriminator: ReadonlyUint8Array;
  entranceCost: bigint;
};

export type UpdateChallengeTemplateEntranceCostInstructionDataArgs = {
  entranceCost: number | bigint;
};

export function getUpdateChallengeTemplateEntranceCostInstructionDataEncoder(): FixedSizeEncoder<UpdateChallengeTemplateEntranceCostInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['entranceCost', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_COST_DISCRIMINATOR,
    })
  );
}

export function getUpdateChallengeTemplateEntranceCostInstructionDataDecoder(): FixedSizeDecoder<UpdateChallengeTemplateEntranceCostInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['entranceCost', getU64Decoder()],
  ]);
}

export function getUpdateChallengeTemplateEntranceCostInstructionDataCodec(): FixedSizeCodec<
  UpdateChallengeTemplateEntranceCostInstructionDataArgs,
  UpdateChallengeTemplateEntranceCostInstructionData
> {
  return combineCodec(
    getUpdateChallengeTemplateEntranceCostInstructionDataEncoder(),
    getUpdateChallengeTemplateEntranceCostInstructionDataDecoder()
  );
}

export type UpdateChallengeTemplateEntranceCostInput<
  TAccountChallengeTemplateAccount extends string = string,
  TAccountSigner extends string = string,
> = {
  challengeTemplateAccount: Address<TAccountChallengeTemplateAccount>;
  signer: TransactionSigner<TAccountSigner>;
  entranceCost: UpdateChallengeTemplateEntranceCostInstructionDataArgs['entranceCost'];
};

export function getUpdateChallengeTemplateEntranceCostInstruction<
  TAccountChallengeTemplateAccount extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: UpdateChallengeTemplateEntranceCostInput<
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateChallengeTemplateEntranceCostInstruction<
  TProgramAddress,
  TAccountChallengeTemplateAccount,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeTemplateAccount: {
      value: input.challengeTemplateAccount ?? null,
      isWritable: true,
    },
    signer: { value: input.signer ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.challengeTemplateAccount),
      getAccountMeta(accounts.signer),
    ],
    data: getUpdateChallengeTemplateEntranceCostInstructionDataEncoder().encode(
      args as UpdateChallengeTemplateEntranceCostInstructionDataArgs
    ),
    programAddress,
  } as UpdateChallengeTemplateEntranceCostInstruction<
    TProgramAddress,
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >);
}

export type ParsedUpdateChallengeTemplateEntranceCostInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeTemplateAccount: TAccountMetas[0];
    signer: TAccountMetas[1];
  };
  data: UpdateChallengeTemplateEntranceCostInstructionData;
};

export function parseUpdateChallengeTemplateEntranceCostInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateChallengeTemplateEntranceCostInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeTemplateAccount: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getUpdateChallengeTemplateEntranceCostInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
