/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getChallengeTemplateUpdateInsertDtoDecoder,
  getChallengeTemplateUpdateInsertDtoEncoder,
  type ChallengeTemplateUpdateInsertDto,
  type ChallengeTemplateUpdateInsertDtoArgs,
} from "../types";

export const UPDATE_CHALLENGE_TEMPLATE_DISCRIMINATOR = new Uint8Array([
  114, 162, 103, 83, 47, 148, 138, 174,
]);

export function getUpdateChallengeTemplateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CHALLENGE_TEMPLATE_DISCRIMINATOR,
  );
}

export type UpdateChallengeTemplateInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeTemplateAccount extends string | AccountMeta<string> =
    string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeTemplateAccount extends string
        ? WritableAccount<TAccountChallengeTemplateAccount>
        : TAccountChallengeTemplateAccount,
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateChallengeTemplateInstructionData = {
  discriminator: ReadonlyUint8Array;
  dto: ChallengeTemplateUpdateInsertDto;
};

export type UpdateChallengeTemplateInstructionDataArgs = {
  dto: ChallengeTemplateUpdateInsertDtoArgs;
};

export function getUpdateChallengeTemplateInstructionDataEncoder(): FixedSizeEncoder<UpdateChallengeTemplateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["dto", getChallengeTemplateUpdateInsertDtoEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_CHALLENGE_TEMPLATE_DISCRIMINATOR,
    }),
  );
}

export function getUpdateChallengeTemplateInstructionDataDecoder(): FixedSizeDecoder<UpdateChallengeTemplateInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["dto", getChallengeTemplateUpdateInsertDtoDecoder()],
  ]);
}

export function getUpdateChallengeTemplateInstructionDataCodec(): FixedSizeCodec<
  UpdateChallengeTemplateInstructionDataArgs,
  UpdateChallengeTemplateInstructionData
> {
  return combineCodec(
    getUpdateChallengeTemplateInstructionDataEncoder(),
    getUpdateChallengeTemplateInstructionDataDecoder(),
  );
}

export type UpdateChallengeTemplateInput<
  TAccountChallengeTemplateAccount extends string = string,
  TAccountSigner extends string = string,
> = {
  challengeTemplateAccount: Address<TAccountChallengeTemplateAccount>;
  signer: TransactionSigner<TAccountSigner>;
  dto: UpdateChallengeTemplateInstructionDataArgs["dto"];
};

export function getUpdateChallengeTemplateInstruction<
  TAccountChallengeTemplateAccount extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: UpdateChallengeTemplateInput<
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateChallengeTemplateInstruction<
  TProgramAddress,
  TAccountChallengeTemplateAccount,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeTemplateAccount: {
      value: input.challengeTemplateAccount ?? null,
      isWritable: true,
    },
    signer: { value: input.signer ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.challengeTemplateAccount),
      getAccountMeta(accounts.signer),
    ],
    data: getUpdateChallengeTemplateInstructionDataEncoder().encode(
      args as UpdateChallengeTemplateInstructionDataArgs,
    ),
    programAddress,
  } as UpdateChallengeTemplateInstruction<
    TProgramAddress,
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >);
}

export type ParsedUpdateChallengeTemplateInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeTemplateAccount: TAccountMetas[0];
    signer: TAccountMetas[1];
  };
  data: UpdateChallengeTemplateInstructionData;
};

export function parseUpdateChallengeTemplateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateChallengeTemplateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeTemplateAccount: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getUpdateChallengeTemplateInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
