/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_TOKEN_MINT_DISCRIMINATOR =
  new Uint8Array([94, 23, 238, 69, 73, 130, 153, 89]);

export function getUpdateChallengeTemplateEntranceTokenMintDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_TOKEN_MINT_DISCRIMINATOR
  );
}

export type UpdateChallengeTemplateEntranceTokenMintInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeTemplateAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeTemplateAccount extends string
        ? WritableAccount<TAccountChallengeTemplateAccount>
        : TAccountChallengeTemplateAccount,
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateChallengeTemplateEntranceTokenMintInstructionData = {
  discriminator: ReadonlyUint8Array;
  entranceTokenMint: Address;
};

export type UpdateChallengeTemplateEntranceTokenMintInstructionDataArgs = {
  entranceTokenMint: Address;
};

export function getUpdateChallengeTemplateEntranceTokenMintInstructionDataEncoder(): FixedSizeEncoder<UpdateChallengeTemplateEntranceTokenMintInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['entranceTokenMint', getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator:
        UPDATE_CHALLENGE_TEMPLATE_ENTRANCE_TOKEN_MINT_DISCRIMINATOR,
    })
  );
}

export function getUpdateChallengeTemplateEntranceTokenMintInstructionDataDecoder(): FixedSizeDecoder<UpdateChallengeTemplateEntranceTokenMintInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['entranceTokenMint', getAddressDecoder()],
  ]);
}

export function getUpdateChallengeTemplateEntranceTokenMintInstructionDataCodec(): FixedSizeCodec<
  UpdateChallengeTemplateEntranceTokenMintInstructionDataArgs,
  UpdateChallengeTemplateEntranceTokenMintInstructionData
> {
  return combineCodec(
    getUpdateChallengeTemplateEntranceTokenMintInstructionDataEncoder(),
    getUpdateChallengeTemplateEntranceTokenMintInstructionDataDecoder()
  );
}

export type UpdateChallengeTemplateEntranceTokenMintInput<
  TAccountChallengeTemplateAccount extends string = string,
  TAccountSigner extends string = string,
> = {
  challengeTemplateAccount: Address<TAccountChallengeTemplateAccount>;
  signer: TransactionSigner<TAccountSigner>;
  entranceTokenMint: UpdateChallengeTemplateEntranceTokenMintInstructionDataArgs['entranceTokenMint'];
};

export function getUpdateChallengeTemplateEntranceTokenMintInstruction<
  TAccountChallengeTemplateAccount extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: UpdateChallengeTemplateEntranceTokenMintInput<
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateChallengeTemplateEntranceTokenMintInstruction<
  TProgramAddress,
  TAccountChallengeTemplateAccount,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeTemplateAccount: {
      value: input.challengeTemplateAccount ?? null,
      isWritable: true,
    },
    signer: { value: input.signer ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.challengeTemplateAccount),
      getAccountMeta(accounts.signer),
    ],
    data: getUpdateChallengeTemplateEntranceTokenMintInstructionDataEncoder().encode(
      args as UpdateChallengeTemplateEntranceTokenMintInstructionDataArgs
    ),
    programAddress,
  } as UpdateChallengeTemplateEntranceTokenMintInstruction<
    TProgramAddress,
    TAccountChallengeTemplateAccount,
    TAccountSigner
  >);
}

export type ParsedUpdateChallengeTemplateEntranceTokenMintInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeTemplateAccount: TAccountMetas[0];
    signer: TAccountMetas[1];
  };
  data: UpdateChallengeTemplateEntranceTokenMintInstructionData;
};

export function parseUpdateChallengeTemplateEntranceTokenMintInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateChallengeTemplateEntranceTokenMintInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeTemplateAccount: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getUpdateChallengeTemplateEntranceTokenMintInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
