/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedInitializeOwnersInstruction,
  type ParsedValidateInstruction,
} from '../instructions';

export const POLICY_OWNERS_PROGRAM_ADDRESS =
  'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A9qAtEM9Qs' as Address<'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A9qAtEM9Qs'>;

export enum PolicyOwnersAccount {
  Owners,
}

export function identifyPolicyOwnersAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyOwnersAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([96, 145, 150, 191, 50, 61, 92, 51])
      ),
      0
    )
  ) {
    return PolicyOwnersAccount.Owners;
  }
  throw new Error(
    'The provided account could not be identified as a policyOwners account.'
  );
}

export enum PolicyOwnersInstruction {
  InitializeOwners,
  Validate,
}

export function identifyPolicyOwnersInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyOwnersInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([145, 41, 103, 101, 229, 205, 135, 157])
      ),
      0
    )
  ) {
    return PolicyOwnersInstruction.InitializeOwners;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 252, 90, 66, 246, 253, 232, 139])
      ),
      0
    )
  ) {
    return PolicyOwnersInstruction.Validate;
  }
  throw new Error(
    'The provided instruction could not be identified as a policyOwners instruction.'
  );
}

export type ParsedPolicyOwnersInstruction<
  TProgram extends string = 'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A9qAtEM9Qs',
> =
  | ({
      instructionType: PolicyOwnersInstruction.InitializeOwners;
    } & ParsedInitializeOwnersInstruction<TProgram>)
  | ({
      instructionType: PolicyOwnersInstruction.Validate;
    } & ParsedValidateInstruction<TProgram>);
