/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPPER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const TRANSFER_LAMPORTS_DISCRIMINATOR = new Uint8Array([
  62, 53, 201, 68, 102, 134, 83, 103,
]);

export function getTransferLamportsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_LAMPORTS_DISCRIMINATOR,
  );
}

export type TransferLamportsInstruction<
  TProgram extends string = typeof DROPPER_PROGRAM_ADDRESS,
  TAccountFrom extends string | AccountMeta<string> = string,
  TAccountTo extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountFrom extends string
        ? WritableSignerAccount<TAccountFrom> & AccountSignerMeta<TAccountFrom>
        : TAccountFrom,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TransferLamportsInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type TransferLamportsInstructionDataArgs = { amount: number | bigint };

export function getTransferLamportsInstructionDataEncoder(): FixedSizeEncoder<TransferLamportsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_LAMPORTS_DISCRIMINATOR }),
  );
}

export function getTransferLamportsInstructionDataDecoder(): FixedSizeDecoder<TransferLamportsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getTransferLamportsInstructionDataCodec(): FixedSizeCodec<
  TransferLamportsInstructionDataArgs,
  TransferLamportsInstructionData
> {
  return combineCodec(
    getTransferLamportsInstructionDataEncoder(),
    getTransferLamportsInstructionDataDecoder(),
  );
}

export type TransferLamportsInput<
  TAccountFrom extends string = string,
  TAccountTo extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  from: TransactionSigner<TAccountFrom>;
  to: Address<TAccountTo>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: TransferLamportsInstructionDataArgs["amount"];
};

export function getTransferLamportsInstruction<
  TAccountFrom extends string,
  TAccountTo extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPPER_PROGRAM_ADDRESS,
>(
  input: TransferLamportsInput<TAccountFrom, TAccountTo, TAccountSystemProgram>,
  config?: { programAddress?: TProgramAddress },
): TransferLamportsInstruction<
  TProgramAddress,
  TAccountFrom,
  TAccountTo,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? DROPPER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    from: { value: input.from ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.from),
      getAccountMeta(accounts.to),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getTransferLamportsInstructionDataEncoder().encode(
      args as TransferLamportsInstructionDataArgs,
    ),
    programAddress,
  } as TransferLamportsInstruction<
    TProgramAddress,
    TAccountFrom,
    TAccountTo,
    TAccountSystemProgram
  >);
}

export type ParsedTransferLamportsInstruction<
  TProgram extends string = typeof DROPPER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    from: TAccountMetas[0];
    to: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: TransferLamportsInstructionData;
};

export function parseTransferLamportsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferLamportsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      from: getNextAccount(),
      to: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getTransferLamportsInstructionDataDecoder().decode(instruction.data),
  };
}
