/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const REVENUE_GENERATOR_DISCRIMINATOR = new Uint8Array([
  11, 124, 77, 223, 158, 124, 234, 56,
]);

export function getRevenueGeneratorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVENUE_GENERATOR_DISCRIMINATOR,
  );
}

export type RevenueGenerator = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  underlyingMint: Address;
  rewardsPerCycle: bigint;
  totalRewardsGenerated: bigint;
  lastMintSlot: bigint;
  bump: number;
};

export type RevenueGeneratorArgs = {
  authority: Address;
  underlyingMint: Address;
  rewardsPerCycle: number | bigint;
  totalRewardsGenerated: number | bigint;
  lastMintSlot: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link RevenueGeneratorArgs} account data. */
export function getRevenueGeneratorEncoder(): FixedSizeEncoder<RevenueGeneratorArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["underlyingMint", getAddressEncoder()],
      ["rewardsPerCycle", getU64Encoder()],
      ["totalRewardsGenerated", getU64Encoder()],
      ["lastMintSlot", getU64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REVENUE_GENERATOR_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link RevenueGenerator} account data. */
export function getRevenueGeneratorDecoder(): FixedSizeDecoder<RevenueGenerator> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["underlyingMint", getAddressDecoder()],
    ["rewardsPerCycle", getU64Decoder()],
    ["totalRewardsGenerated", getU64Decoder()],
    ["lastMintSlot", getU64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link RevenueGenerator} account data. */
export function getRevenueGeneratorCodec(): FixedSizeCodec<
  RevenueGeneratorArgs,
  RevenueGenerator
> {
  return combineCodec(
    getRevenueGeneratorEncoder(),
    getRevenueGeneratorDecoder(),
  );
}

export function decodeRevenueGenerator<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RevenueGenerator, TAddress>;
export function decodeRevenueGenerator<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RevenueGenerator, TAddress>;
export function decodeRevenueGenerator<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<RevenueGenerator, TAddress>
  | MaybeAccount<RevenueGenerator, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRevenueGeneratorDecoder(),
  );
}

export async function fetchRevenueGenerator<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RevenueGenerator, TAddress>> {
  const maybeAccount = await fetchMaybeRevenueGenerator(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRevenueGenerator<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RevenueGenerator, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRevenueGenerator(maybeAccount);
}

export async function fetchAllRevenueGenerator(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<RevenueGenerator>[]> {
  const maybeAccounts = await fetchAllMaybeRevenueGenerator(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRevenueGenerator(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RevenueGenerator>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeRevenueGenerator(maybeAccount),
  );
}

export function getRevenueGeneratorSize(): number {
  return 97;
}
