/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';
import {
  getTimeBasedFeeEntryDecoder,
  getTimeBasedFeeEntryEncoder,
  type TimeBasedFeeEntry,
  type TimeBasedFeeEntryArgs,
} from '.';

/** Time-based fee configuration */
export type TimeBasedFeeConfig = {
  /** LP fee configuration */
  lp: TimeBasedFeeEntry;
  /** Manager fee configuration (e.g., management company salary) */
  manager: TimeBasedFeeEntry;
  /** Protocol fee configuration */
  protocol: TimeBasedFeeEntry;
  /** Performance fee configuration (typically not time-based, but supported) */
  performance: TimeBasedFeeEntry;
};

export type TimeBasedFeeConfigArgs = {
  /** LP fee configuration */
  lp: TimeBasedFeeEntryArgs;
  /** Manager fee configuration (e.g., management company salary) */
  manager: TimeBasedFeeEntryArgs;
  /** Protocol fee configuration */
  protocol: TimeBasedFeeEntryArgs;
  /** Performance fee configuration (typically not time-based, but supported) */
  performance: TimeBasedFeeEntryArgs;
};

export function getTimeBasedFeeConfigEncoder(): FixedSizeEncoder<TimeBasedFeeConfigArgs> {
  return getStructEncoder([
    ['lp', getTimeBasedFeeEntryEncoder()],
    ['manager', getTimeBasedFeeEntryEncoder()],
    ['protocol', getTimeBasedFeeEntryEncoder()],
    ['performance', getTimeBasedFeeEntryEncoder()],
  ]);
}

export function getTimeBasedFeeConfigDecoder(): FixedSizeDecoder<TimeBasedFeeConfig> {
  return getStructDecoder([
    ['lp', getTimeBasedFeeEntryDecoder()],
    ['manager', getTimeBasedFeeEntryDecoder()],
    ['protocol', getTimeBasedFeeEntryDecoder()],
    ['performance', getTimeBasedFeeEntryDecoder()],
  ]);
}

export function getTimeBasedFeeConfigCodec(): FixedSizeCodec<
  TimeBasedFeeConfigArgs,
  TimeBasedFeeConfig
> {
  return combineCodec(
    getTimeBasedFeeConfigEncoder(),
    getTimeBasedFeeConfigDecoder()
  );
}
