/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedInitializeManagersInstruction,
  type ParsedValidateInstruction,
} from '../instructions';

export const POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS =
  'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A7qAtEM9Qs' as Address<'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A7qAtEM9Qs'>;

export enum PolicyManagerAccessAccount {
  Managers,
}

export function identifyPolicyManagerAccessAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyManagerAccessAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([50, 116, 200, 15, 255, 219, 93, 254])
      ),
      0
    )
  ) {
    return PolicyManagerAccessAccount.Managers;
  }
  throw new Error(
    'The provided account could not be identified as a policyManagerAccess account.'
  );
}

export enum PolicyManagerAccessInstruction {
  InitializeManagers,
  Validate,
}

export function identifyPolicyManagerAccessInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyManagerAccessInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([184, 12, 75, 43, 10, 73, 29, 155])
      ),
      0
    )
  ) {
    return PolicyManagerAccessInstruction.InitializeManagers;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 252, 90, 66, 246, 253, 232, 139])
      ),
      0
    )
  ) {
    return PolicyManagerAccessInstruction.Validate;
  }
  throw new Error(
    'The provided instruction could not be identified as a policyManagerAccess instruction.'
  );
}

export type ParsedPolicyManagerAccessInstruction<
  TProgram extends string = 'HyroXELvGkzBwgKz2Fsz2XEMDM6TYupZZ1A7qAtEM9Qs',
> =
  | ({
      instructionType: PolicyManagerAccessInstruction.InitializeManagers;
    } & ParsedInitializeManagersInstruction<TProgram>)
  | ({
      instructionType: PolicyManagerAccessInstruction.Validate;
    } & ParsedValidateInstruction<TProgram>);
