/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getAllInOneConfigDecoder,
  getAllInOneConfigEncoder,
  type AllInOneConfig,
  type AllInOneConfigArgs,
} from '../types';

export const VAULT_ALL_IN_ONE_CONFIG_DISCRIMINATOR = new Uint8Array([
  124, 88, 126, 126, 39, 118, 51, 134,
]);

export function getVaultAllInOneConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VAULT_ALL_IN_ONE_CONFIG_DISCRIMINATOR
  );
}

export type VaultAllInOneConfig = {
  discriminator: ReadonlyUint8Array;
  /** The vault this config belongs to */
  vault: Address;
  /** Combined fee configuration */
  config: AllInOneConfig;
  /** Last calculation timestamp for each time-based fee type */
  lastLpCalc: bigint;
  lastManagerCalc: bigint;
  lastProtocolCalc: bigint;
  lastPerformanceCalc: bigint;
  /** High water mark for performance fees */
  highWaterMark: bigint;
  /** Bump seed */
  bump: number;
};

export type VaultAllInOneConfigArgs = {
  /** The vault this config belongs to */
  vault: Address;
  /** Combined fee configuration */
  config: AllInOneConfigArgs;
  /** Last calculation timestamp for each time-based fee type */
  lastLpCalc: number | bigint;
  lastManagerCalc: number | bigint;
  lastProtocolCalc: number | bigint;
  lastPerformanceCalc: number | bigint;
  /** High water mark for performance fees */
  highWaterMark: number | bigint;
  /** Bump seed */
  bump: number;
};

/** Gets the encoder for {@link VaultAllInOneConfigArgs} account data. */
export function getVaultAllInOneConfigEncoder(): FixedSizeEncoder<VaultAllInOneConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['vault', getAddressEncoder()],
      ['config', getAllInOneConfigEncoder()],
      ['lastLpCalc', getI64Encoder()],
      ['lastManagerCalc', getI64Encoder()],
      ['lastProtocolCalc', getI64Encoder()],
      ['lastPerformanceCalc', getI64Encoder()],
      ['highWaterMark', getU64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: VAULT_ALL_IN_ONE_CONFIG_DISCRIMINATOR,
    })
  );
}

/** Gets the decoder for {@link VaultAllInOneConfig} account data. */
export function getVaultAllInOneConfigDecoder(): FixedSizeDecoder<VaultAllInOneConfig> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['vault', getAddressDecoder()],
    ['config', getAllInOneConfigDecoder()],
    ['lastLpCalc', getI64Decoder()],
    ['lastManagerCalc', getI64Decoder()],
    ['lastProtocolCalc', getI64Decoder()],
    ['lastPerformanceCalc', getI64Decoder()],
    ['highWaterMark', getU64Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

/** Gets the codec for {@link VaultAllInOneConfig} account data. */
export function getVaultAllInOneConfigCodec(): FixedSizeCodec<
  VaultAllInOneConfigArgs,
  VaultAllInOneConfig
> {
  return combineCodec(
    getVaultAllInOneConfigEncoder(),
    getVaultAllInOneConfigDecoder()
  );
}

export function decodeVaultAllInOneConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<VaultAllInOneConfig, TAddress>;
export function decodeVaultAllInOneConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<VaultAllInOneConfig, TAddress>;
export function decodeVaultAllInOneConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<VaultAllInOneConfig, TAddress>
  | MaybeAccount<VaultAllInOneConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVaultAllInOneConfigDecoder()
  );
}

export async function fetchVaultAllInOneConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<VaultAllInOneConfig, TAddress>> {
  const maybeAccount = await fetchMaybeVaultAllInOneConfig(
    rpc,
    address,
    config
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVaultAllInOneConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<VaultAllInOneConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVaultAllInOneConfig(maybeAccount);
}

export async function fetchAllVaultAllInOneConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<VaultAllInOneConfig>[]> {
  const maybeAccounts = await fetchAllMaybeVaultAllInOneConfig(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVaultAllInOneConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<VaultAllInOneConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeVaultAllInOneConfig(maybeAccount)
  );
}

export function getVaultAllInOneConfigSize(): number {
  return 137;
}
