/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getTimeBasedConfigDecoder,
  getTimeBasedConfigEncoder,
  type TimeBasedConfig,
  type TimeBasedConfigArgs,
} from "../types";

export const UPDATE_TIME_BASED_CONFIG_DISCRIMINATOR = new Uint8Array([
  1, 170, 161, 15, 4, 42, 89, 118,
]);

export function getUpdateTimeBasedConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_TIME_BASED_CONFIG_DISCRIMINATOR,
  );
}

export type UpdateTimeBasedConfigInstruction<
  TProgram extends string = typeof FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountConfigAccount extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountConfigAccount extends string
        ? WritableAccount<TAccountConfigAccount>
        : TAccountConfigAccount,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateTimeBasedConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  timeBased: TimeBasedConfig;
};

export type UpdateTimeBasedConfigInstructionDataArgs = {
  timeBased: TimeBasedConfigArgs;
};

export function getUpdateTimeBasedConfigInstructionDataEncoder(): FixedSizeEncoder<UpdateTimeBasedConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["timeBased", getTimeBasedConfigEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_TIME_BASED_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getUpdateTimeBasedConfigInstructionDataDecoder(): FixedSizeDecoder<UpdateTimeBasedConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["timeBased", getTimeBasedConfigDecoder()],
  ]);
}

export function getUpdateTimeBasedConfigInstructionDataCodec(): FixedSizeCodec<
  UpdateTimeBasedConfigInstructionDataArgs,
  UpdateTimeBasedConfigInstructionData
> {
  return combineCodec(
    getUpdateTimeBasedConfigInstructionDataEncoder(),
    getUpdateTimeBasedConfigInstructionDataDecoder(),
  );
}

export type UpdateTimeBasedConfigAsyncInput<
  TAccountVault extends string = string,
  TAccountConfigAccount extends string = string,
  TAccountAuthority extends string = string,
> = {
  vault: Address<TAccountVault>;
  configAccount?: Address<TAccountConfigAccount>;
  /** Authority that can update config (typically vault admin) */
  authority: TransactionSigner<TAccountAuthority>;
  timeBased: UpdateTimeBasedConfigInstructionDataArgs["timeBased"];
};

export async function getUpdateTimeBasedConfigInstructionAsync<
  TAccountVault extends string,
  TAccountConfigAccount extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address =
    typeof FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS,
>(
  input: UpdateTimeBasedConfigAsyncInput<
    TAccountVault,
    TAccountConfigAccount,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateTimeBasedConfigInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountConfigAccount,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    configAccount: { value: input.configAccount ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.configAccount.value) {
    accounts.configAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 108, 108, 95, 105, 110, 95, 111, 110, 101, 95, 99, 111, 110,
            102, 105, 103,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.configAccount),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateTimeBasedConfigInstructionDataEncoder().encode(
      args as UpdateTimeBasedConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateTimeBasedConfigInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountConfigAccount,
    TAccountAuthority
  >);
}

export type UpdateTimeBasedConfigInput<
  TAccountVault extends string = string,
  TAccountConfigAccount extends string = string,
  TAccountAuthority extends string = string,
> = {
  vault: Address<TAccountVault>;
  configAccount: Address<TAccountConfigAccount>;
  /** Authority that can update config (typically vault admin) */
  authority: TransactionSigner<TAccountAuthority>;
  timeBased: UpdateTimeBasedConfigInstructionDataArgs["timeBased"];
};

export function getUpdateTimeBasedConfigInstruction<
  TAccountVault extends string,
  TAccountConfigAccount extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address =
    typeof FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS,
>(
  input: UpdateTimeBasedConfigInput<
    TAccountVault,
    TAccountConfigAccount,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateTimeBasedConfigInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountConfigAccount,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    configAccount: { value: input.configAccount ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.configAccount),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateTimeBasedConfigInstructionDataEncoder().encode(
      args as UpdateTimeBasedConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateTimeBasedConfigInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountConfigAccount,
    TAccountAuthority
  >);
}

export type ParsedUpdateTimeBasedConfigInstruction<
  TProgram extends string = typeof FEE_COLLECTION_ALL_IN_ONE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    configAccount: TAccountMetas[1];
    /** Authority that can update config (typically vault admin) */
    authority: TAccountMetas[2];
  };
  data: UpdateTimeBasedConfigInstructionData;
};

export function parseUpdateTimeBasedConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateTimeBasedConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      configAccount: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getUpdateTimeBasedConfigInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
