/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getTransactionAccountDecoder,
  getTransactionAccountEncoder,
  type TransactionAccount,
  type TransactionAccountArgs,
} from "../types";

export const CREATE_TX_DISCRIMINATOR = new Uint8Array([
  97, 223, 80, 153, 55, 13, 155, 12,
]);

export function getCreateTxDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CREATE_TX_DISCRIMINATOR);
}

export type CreateTxInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountPolicyAccount extends string | AccountMeta<string> = string,
  TAccountPolicyProgram extends string | AccountMeta<string> = string,
  TAccountVaultSigner extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountPolicyAccount extends string
        ? WritableAccount<TAccountPolicyAccount>
        : TAccountPolicyAccount,
      TAccountPolicyProgram extends string
        ? ReadonlyAccount<TAccountPolicyProgram>
        : TAccountPolicyProgram,
      TAccountVaultSigner extends string
        ? ReadonlyAccount<TAccountVaultSigner>
        : TAccountVaultSigner,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateTxInstructionData = {
  discriminator: ReadonlyUint8Array;
  nonce: bigint;
  pid: Address;
  accs: Array<TransactionAccount>;
  data: ReadonlyUint8Array;
};

export type CreateTxInstructionDataArgs = {
  nonce: number | bigint;
  pid: Address;
  accs: Array<TransactionAccountArgs>;
  data: ReadonlyUint8Array;
};

export function getCreateTxInstructionDataEncoder(): Encoder<CreateTxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["nonce", getU64Encoder()],
      ["pid", getAddressEncoder()],
      ["accs", getArrayEncoder(getTransactionAccountEncoder())],
      ["data", addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CREATE_TX_DISCRIMINATOR }),
  );
}

export function getCreateTxInstructionDataDecoder(): Decoder<CreateTxInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["nonce", getU64Decoder()],
    ["pid", getAddressDecoder()],
    ["accs", getArrayDecoder(getTransactionAccountDecoder())],
    ["data", addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getCreateTxInstructionDataCodec(): Codec<
  CreateTxInstructionDataArgs,
  CreateTxInstructionData
> {
  return combineCodec(
    getCreateTxInstructionDataEncoder(),
    getCreateTxInstructionDataDecoder(),
  );
}

export type CreateTxAsyncInput<
  TAccountVault extends string = string,
  TAccountTransaction extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountVaultSigner extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  transaction?: Address<TAccountTransaction>;
  policyAccount: Address<TAccountPolicyAccount>;
  policyProgram: Address<TAccountPolicyProgram>;
  vaultSigner?: Address<TAccountVaultSigner>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  nonce: CreateTxInstructionDataArgs["nonce"];
  pid: CreateTxInstructionDataArgs["pid"];
  accs: CreateTxInstructionDataArgs["accs"];
  data: CreateTxInstructionDataArgs["data"];
};

export async function getCreateTxInstructionAsync<
  TAccountVault extends string,
  TAccountTransaction extends string,
  TAccountPolicyAccount extends string,
  TAccountPolicyProgram extends string,
  TAccountVaultSigner extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CreateTxAsyncInput<
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountVaultSigner,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountVaultSigner,
    TAccountSigner,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    vaultSigner: { value: input.vaultSigner ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.transaction.value) {
    accounts.transaction.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getU64Encoder().encode(expectSome(args.nonce)),
      ],
    });
  }
  if (!accounts.vaultSigner.value) {
    accounts.vaultSigner.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getAddressEncoder().encode(expectAddress(accounts.vault.value))],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.vaultSigner),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateTxInstructionDataEncoder().encode(
      args as CreateTxInstructionDataArgs,
    ),
    programAddress,
  } as CreateTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountVaultSigner,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type CreateTxInput<
  TAccountVault extends string = string,
  TAccountTransaction extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountVaultSigner extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  transaction: Address<TAccountTransaction>;
  policyAccount: Address<TAccountPolicyAccount>;
  policyProgram: Address<TAccountPolicyProgram>;
  vaultSigner: Address<TAccountVaultSigner>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  nonce: CreateTxInstructionDataArgs["nonce"];
  pid: CreateTxInstructionDataArgs["pid"];
  accs: CreateTxInstructionDataArgs["accs"];
  data: CreateTxInstructionDataArgs["data"];
};

export function getCreateTxInstruction<
  TAccountVault extends string,
  TAccountTransaction extends string,
  TAccountPolicyAccount extends string,
  TAccountPolicyProgram extends string,
  TAccountVaultSigner extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: CreateTxInput<
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountVaultSigner,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateTxInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountTransaction,
  TAccountPolicyAccount,
  TAccountPolicyProgram,
  TAccountVaultSigner,
  TAccountSigner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: true },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    vaultSigner: { value: input.vaultSigner ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.vaultSigner),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateTxInstructionDataEncoder().encode(
      args as CreateTxInstructionDataArgs,
    ),
    programAddress,
  } as CreateTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountVaultSigner,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type ParsedCreateTxInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    transaction: TAccountMetas[1];
    policyAccount: TAccountMetas[2];
    policyProgram: TAccountMetas[3];
    vaultSigner: TAccountMetas[4];
    signer: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: CreateTxInstructionData;
};

export function parseCreateTxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateTxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      transaction: getNextAccount(),
      policyAccount: getNextAccount(),
      policyProgram: getNextAccount(),
      vaultSigner: getNextAccount(),
      signer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateTxInstructionDataDecoder().decode(instruction.data),
  };
}
