/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const DEPOSIT_ASSETS_DISCRIMINATOR = new Uint8Array([
  8, 21, 152, 34, 223, 94, 7, 176,
]);

export function getDepositAssetsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DEPOSIT_ASSETS_DISCRIMINATOR,
  );
}

export type DepositAssetsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountShareSignerPda extends string | AccountMeta<string> = string,
  TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountSenderTokenAccount extends string | AccountMeta<string> = string,
  TAccountSenderShareAccount extends string | AccountMeta<string> = string,
  TAccountShareMint extends string | AccountMeta<string> = string,
  TAccountUnderlyingMint extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountFeeCollectionProgram extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountHyroProtocol extends string | AccountMeta<string> =
    "7gx2mxou2JwuBNiDhfPeXf8EVK8DUGnXPLKdiyYKT3NL",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountShareSignerPda extends string
        ? ReadonlyAccount<TAccountShareSignerPda>
        : TAccountShareSignerPda,
      TAccountVaultTokenAccount extends string
        ? WritableAccount<TAccountVaultTokenAccount>
        : TAccountVaultTokenAccount,
      TAccountSenderTokenAccount extends string
        ? WritableAccount<TAccountSenderTokenAccount>
        : TAccountSenderTokenAccount,
      TAccountSenderShareAccount extends string
        ? WritableAccount<TAccountSenderShareAccount>
        : TAccountSenderShareAccount,
      TAccountShareMint extends string
        ? WritableAccount<TAccountShareMint>
        : TAccountShareMint,
      TAccountUnderlyingMint extends string
        ? WritableAccount<TAccountUnderlyingMint>
        : TAccountUnderlyingMint,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountFeeCollectionProgram extends string
        ? ReadonlyAccount<TAccountFeeCollectionProgram>
        : TAccountFeeCollectionProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountHyroProtocol extends string
        ? ReadonlyAccount<TAccountHyroProtocol>
        : TAccountHyroProtocol,
      ...TRemainingAccounts,
    ]
  >;

export type DepositAssetsInstructionData = {
  discriminator: ReadonlyUint8Array;
  assets: bigint;
};

export type DepositAssetsInstructionDataArgs = { assets: number | bigint };

export function getDepositAssetsInstructionDataEncoder(): FixedSizeEncoder<DepositAssetsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["assets", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_ASSETS_DISCRIMINATOR }),
  );
}

export function getDepositAssetsInstructionDataDecoder(): FixedSizeDecoder<DepositAssetsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["assets", getU64Decoder()],
  ]);
}

export function getDepositAssetsInstructionDataCodec(): FixedSizeCodec<
  DepositAssetsInstructionDataArgs,
  DepositAssetsInstructionData
> {
  return combineCodec(
    getDepositAssetsInstructionDataEncoder(),
    getDepositAssetsInstructionDataDecoder(),
  );
}

export type DepositAssetsAsyncInput<
  TAccountShareSignerPda extends string = string,
  TAccountVaultTokenAccount extends string = string,
  TAccountSenderTokenAccount extends string = string,
  TAccountSenderShareAccount extends string = string,
  TAccountShareMint extends string = string,
  TAccountUnderlyingMint extends string = string,
  TAccountVault extends string = string,
  TAccountFeeCollectionProgram extends string = string,
  TAccountSigner extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountHyroProtocol extends string = string,
> = {
  shareSignerPda?: Address<TAccountShareSignerPda>;
  vaultTokenAccount?: Address<TAccountVaultTokenAccount>;
  senderTokenAccount: Address<TAccountSenderTokenAccount>;
  senderShareAccount: Address<TAccountSenderShareAccount>;
  shareMint?: Address<TAccountShareMint>;
  underlyingMint: Address<TAccountUnderlyingMint>;
  vault: Address<TAccountVault>;
  feeCollectionProgram: Address<TAccountFeeCollectionProgram>;
  signer: TransactionSigner<TAccountSigner>;
  tokenProgram?: Address<TAccountTokenProgram>;
  hyroProtocol?: Address<TAccountHyroProtocol>;
  assets: DepositAssetsInstructionDataArgs["assets"];
};

export async function getDepositAssetsInstructionAsync<
  TAccountShareSignerPda extends string,
  TAccountVaultTokenAccount extends string,
  TAccountSenderTokenAccount extends string,
  TAccountSenderShareAccount extends string,
  TAccountShareMint extends string,
  TAccountUnderlyingMint extends string,
  TAccountVault extends string,
  TAccountFeeCollectionProgram extends string,
  TAccountSigner extends string,
  TAccountTokenProgram extends string,
  TAccountHyroProtocol extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: DepositAssetsAsyncInput<
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountSenderTokenAccount,
    TAccountSenderShareAccount,
    TAccountShareMint,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram,
    TAccountHyroProtocol
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DepositAssetsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountSenderTokenAccount,
    TAccountSenderShareAccount,
    TAccountShareMint,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram,
    TAccountHyroProtocol
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    shareSignerPda: { value: input.shareSignerPda ?? null, isWritable: false },
    vaultTokenAccount: {
      value: input.vaultTokenAccount ?? null,
      isWritable: true,
    },
    senderTokenAccount: {
      value: input.senderTokenAccount ?? null,
      isWritable: true,
    },
    senderShareAccount: {
      value: input.senderShareAccount ?? null,
      isWritable: true,
    },
    shareMint: { value: input.shareMint ?? null, isWritable: true },
    underlyingMint: { value: input.underlyingMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    feeCollectionProgram: {
      value: input.feeCollectionProgram ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    hyroProtocol: { value: input.hyroProtocol ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.shareSignerPda.value) {
    accounts.shareSignerPda.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            118, 97, 117, 108, 116, 95, 115, 104, 97, 114, 101, 95, 115, 105,
            103, 110, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }
  if (!accounts.vaultTokenAccount.value) {
    accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            118, 97, 117, 108, 116, 95, 116, 111, 107, 101, 110, 95, 97, 99, 99,
            111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.underlyingMint.value),
        ),
      ],
    });
  }
  if (!accounts.shareMint.value) {
    accounts.shareMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            118, 97, 117, 108, 116, 95, 115, 104, 97, 114, 101, 95, 109, 105,
            110, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.hyroProtocol.value) {
    accounts.hyroProtocol.value =
      "7gx2mxou2JwuBNiDhfPeXf8EVK8DUGnXPLKdiyYKT3NL" as Address<"7gx2mxou2JwuBNiDhfPeXf8EVK8DUGnXPLKdiyYKT3NL">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.shareSignerPda),
      getAccountMeta(accounts.vaultTokenAccount),
      getAccountMeta(accounts.senderTokenAccount),
      getAccountMeta(accounts.senderShareAccount),
      getAccountMeta(accounts.shareMint),
      getAccountMeta(accounts.underlyingMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.feeCollectionProgram),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.hyroProtocol),
    ],
    data: getDepositAssetsInstructionDataEncoder().encode(
      args as DepositAssetsInstructionDataArgs,
    ),
    programAddress,
  } as DepositAssetsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountSenderTokenAccount,
    TAccountSenderShareAccount,
    TAccountShareMint,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram,
    TAccountHyroProtocol
  >);
}

export type DepositAssetsInput<
  TAccountShareSignerPda extends string = string,
  TAccountVaultTokenAccount extends string = string,
  TAccountSenderTokenAccount extends string = string,
  TAccountSenderShareAccount extends string = string,
  TAccountShareMint extends string = string,
  TAccountUnderlyingMint extends string = string,
  TAccountVault extends string = string,
  TAccountFeeCollectionProgram extends string = string,
  TAccountSigner extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountHyroProtocol extends string = string,
> = {
  shareSignerPda: Address<TAccountShareSignerPda>;
  vaultTokenAccount: Address<TAccountVaultTokenAccount>;
  senderTokenAccount: Address<TAccountSenderTokenAccount>;
  senderShareAccount: Address<TAccountSenderShareAccount>;
  shareMint: Address<TAccountShareMint>;
  underlyingMint: Address<TAccountUnderlyingMint>;
  vault: Address<TAccountVault>;
  feeCollectionProgram: Address<TAccountFeeCollectionProgram>;
  signer: TransactionSigner<TAccountSigner>;
  tokenProgram?: Address<TAccountTokenProgram>;
  hyroProtocol?: Address<TAccountHyroProtocol>;
  assets: DepositAssetsInstructionDataArgs["assets"];
};

export function getDepositAssetsInstruction<
  TAccountShareSignerPda extends string,
  TAccountVaultTokenAccount extends string,
  TAccountSenderTokenAccount extends string,
  TAccountSenderShareAccount extends string,
  TAccountShareMint extends string,
  TAccountUnderlyingMint extends string,
  TAccountVault extends string,
  TAccountFeeCollectionProgram extends string,
  TAccountSigner extends string,
  TAccountTokenProgram extends string,
  TAccountHyroProtocol extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: DepositAssetsInput<
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountSenderTokenAccount,
    TAccountSenderShareAccount,
    TAccountShareMint,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram,
    TAccountHyroProtocol
  >,
  config?: { programAddress?: TProgramAddress },
): DepositAssetsInstruction<
  TProgramAddress,
  TAccountShareSignerPda,
  TAccountVaultTokenAccount,
  TAccountSenderTokenAccount,
  TAccountSenderShareAccount,
  TAccountShareMint,
  TAccountUnderlyingMint,
  TAccountVault,
  TAccountFeeCollectionProgram,
  TAccountSigner,
  TAccountTokenProgram,
  TAccountHyroProtocol
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    shareSignerPda: { value: input.shareSignerPda ?? null, isWritable: false },
    vaultTokenAccount: {
      value: input.vaultTokenAccount ?? null,
      isWritable: true,
    },
    senderTokenAccount: {
      value: input.senderTokenAccount ?? null,
      isWritable: true,
    },
    senderShareAccount: {
      value: input.senderShareAccount ?? null,
      isWritable: true,
    },
    shareMint: { value: input.shareMint ?? null, isWritable: true },
    underlyingMint: { value: input.underlyingMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    feeCollectionProgram: {
      value: input.feeCollectionProgram ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    hyroProtocol: { value: input.hyroProtocol ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.hyroProtocol.value) {
    accounts.hyroProtocol.value =
      "7gx2mxou2JwuBNiDhfPeXf8EVK8DUGnXPLKdiyYKT3NL" as Address<"7gx2mxou2JwuBNiDhfPeXf8EVK8DUGnXPLKdiyYKT3NL">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.shareSignerPda),
      getAccountMeta(accounts.vaultTokenAccount),
      getAccountMeta(accounts.senderTokenAccount),
      getAccountMeta(accounts.senderShareAccount),
      getAccountMeta(accounts.shareMint),
      getAccountMeta(accounts.underlyingMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.feeCollectionProgram),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.hyroProtocol),
    ],
    data: getDepositAssetsInstructionDataEncoder().encode(
      args as DepositAssetsInstructionDataArgs,
    ),
    programAddress,
  } as DepositAssetsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountSenderTokenAccount,
    TAccountSenderShareAccount,
    TAccountShareMint,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram,
    TAccountHyroProtocol
  >);
}

export type ParsedDepositAssetsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    shareSignerPda: TAccountMetas[0];
    vaultTokenAccount: TAccountMetas[1];
    senderTokenAccount: TAccountMetas[2];
    senderShareAccount: TAccountMetas[3];
    shareMint: TAccountMetas[4];
    underlyingMint: TAccountMetas[5];
    vault: TAccountMetas[6];
    feeCollectionProgram: TAccountMetas[7];
    signer: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    hyroProtocol: TAccountMetas[10];
  };
  data: DepositAssetsInstructionData;
};

export function parseDepositAssetsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositAssetsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      shareSignerPda: getNextAccount(),
      vaultTokenAccount: getNextAccount(),
      senderTokenAccount: getNextAccount(),
      senderShareAccount: getNextAccount(),
      shareMint: getNextAccount(),
      underlyingMint: getNextAccount(),
      vault: getNextAccount(),
      feeCollectionProgram: getNextAccount(),
      signer: getNextAccount(),
      tokenProgram: getNextAccount(),
      hyroProtocol: getNextAccount(),
    },
    data: getDepositAssetsInstructionDataDecoder().decode(instruction.data),
  };
}
