/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const EXECUTE_TX_DISCRIMINATOR = new Uint8Array([
  249, 17, 145, 23, 12, 252, 17, 41,
]);

export function getExecuteTxDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(EXECUTE_TX_DISCRIMINATOR);
}

export type ExecuteTxInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountVaultSigner extends string | AccountMeta<string> = string,
  TAccountPolicyAccount extends string | AccountMeta<string> = string,
  TAccountPolicyProgram extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountTransaction extends string
        ? ReadonlyAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountVaultSigner extends string
        ? ReadonlyAccount<TAccountVaultSigner>
        : TAccountVaultSigner,
      TAccountPolicyAccount extends string
        ? WritableAccount<TAccountPolicyAccount>
        : TAccountPolicyAccount,
      TAccountPolicyProgram extends string
        ? ReadonlyAccount<TAccountPolicyProgram>
        : TAccountPolicyProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type ExecuteTxInstructionData = { discriminator: ReadonlyUint8Array };

export type ExecuteTxInstructionDataArgs = {};

export function getExecuteTxInstructionDataEncoder(): FixedSizeEncoder<ExecuteTxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EXECUTE_TX_DISCRIMINATOR }),
  );
}

export function getExecuteTxInstructionDataDecoder(): FixedSizeDecoder<ExecuteTxInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getExecuteTxInstructionDataCodec(): FixedSizeCodec<
  ExecuteTxInstructionDataArgs,
  ExecuteTxInstructionData
> {
  return combineCodec(
    getExecuteTxInstructionDataEncoder(),
    getExecuteTxInstructionDataDecoder(),
  );
}

export type ExecuteTxAsyncInput<
  TAccountVault extends string = string,
  TAccountTransaction extends string = string,
  TAccountVaultSigner extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  vault: Address<TAccountVault>;
  transaction: Address<TAccountTransaction>;
  vaultSigner?: Address<TAccountVaultSigner>;
  policyAccount: Address<TAccountPolicyAccount>;
  policyProgram: Address<TAccountPolicyProgram>;
  signer: TransactionSigner<TAccountSigner>;
};

export async function getExecuteTxInstructionAsync<
  TAccountVault extends string,
  TAccountTransaction extends string,
  TAccountVaultSigner extends string,
  TAccountPolicyAccount extends string,
  TAccountPolicyProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ExecuteTxAsyncInput<
    TAccountVault,
    TAccountTransaction,
    TAccountVaultSigner,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ExecuteTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountVaultSigner,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountSigner
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: false },
    vaultSigner: { value: input.vaultSigner ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.vaultSigner.value) {
    accounts.vaultSigner.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getAddressEncoder().encode(expectAddress(accounts.vault.value))],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.vaultSigner),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.signer),
    ],
    data: getExecuteTxInstructionDataEncoder().encode({}),
    programAddress,
  } as ExecuteTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountVaultSigner,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountSigner
  >);
}

export type ExecuteTxInput<
  TAccountVault extends string = string,
  TAccountTransaction extends string = string,
  TAccountVaultSigner extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  vault: Address<TAccountVault>;
  transaction: Address<TAccountTransaction>;
  vaultSigner: Address<TAccountVaultSigner>;
  policyAccount: Address<TAccountPolicyAccount>;
  policyProgram: Address<TAccountPolicyProgram>;
  signer: TransactionSigner<TAccountSigner>;
};

export function getExecuteTxInstruction<
  TAccountVault extends string,
  TAccountTransaction extends string,
  TAccountVaultSigner extends string,
  TAccountPolicyAccount extends string,
  TAccountPolicyProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ExecuteTxInput<
    TAccountVault,
    TAccountTransaction,
    TAccountVaultSigner,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress },
): ExecuteTxInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountTransaction,
  TAccountVaultSigner,
  TAccountPolicyAccount,
  TAccountPolicyProgram,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: false },
    vaultSigner: { value: input.vaultSigner ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.vaultSigner),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.signer),
    ],
    data: getExecuteTxInstructionDataEncoder().encode({}),
    programAddress,
  } as ExecuteTxInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountVaultSigner,
    TAccountPolicyAccount,
    TAccountPolicyProgram,
    TAccountSigner
  >);
}

export type ParsedExecuteTxInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    transaction: TAccountMetas[1];
    vaultSigner: TAccountMetas[2];
    policyAccount: TAccountMetas[3];
    policyProgram: TAccountMetas[4];
    signer: TAccountMetas[5];
  };
  data: ExecuteTxInstructionData;
};

export function parseExecuteTxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExecuteTxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      transaction: getNextAccount(),
      vaultSigner: getNextAccount(),
      policyAccount: getNextAccount(),
      policyProgram: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getExecuteTxInstructionDataDecoder().decode(instruction.data),
  };
}
