/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getBalanceUpdateDecoder,
  getBalanceUpdateEncoder,
  type BalanceUpdate,
  type BalanceUpdateArgs,
} from '../types';

export const REPORT_ON_FUNDS_DISCRIMINATOR = new Uint8Array([
  106, 224, 151, 62, 55, 104, 47, 191,
]);

export function getReportOnFundsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REPORT_ON_FUNDS_DISCRIMINATOR
  );
}

export type ReportOnFundsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPolicyProgram extends string | AccountMeta<string> = string,
  TAccountFeeCollectionProgram extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountPolicyProgram extends string
        ? ReadonlyAccount<TAccountPolicyProgram>
        : TAccountPolicyProgram,
      TAccountFeeCollectionProgram extends string
        ? ReadonlyAccount<TAccountFeeCollectionProgram>
        : TAccountFeeCollectionProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type ReportOnFundsInstructionData = {
  discriminator: ReadonlyUint8Array;
  balance: BalanceUpdate;
};

export type ReportOnFundsInstructionDataArgs = { balance: BalanceUpdateArgs };

export function getReportOnFundsInstructionDataEncoder(): FixedSizeEncoder<ReportOnFundsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['balance', getBalanceUpdateEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REPORT_ON_FUNDS_DISCRIMINATOR })
  );
}

export function getReportOnFundsInstructionDataDecoder(): FixedSizeDecoder<ReportOnFundsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['balance', getBalanceUpdateDecoder()],
  ]);
}

export function getReportOnFundsInstructionDataCodec(): FixedSizeCodec<
  ReportOnFundsInstructionDataArgs,
  ReportOnFundsInstructionData
> {
  return combineCodec(
    getReportOnFundsInstructionDataEncoder(),
    getReportOnFundsInstructionDataDecoder()
  );
}

export type ReportOnFundsInput<
  TAccountVault extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountFeeCollectionProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  vault: Address<TAccountVault>;
  policyProgram: Address<TAccountPolicyProgram>;
  feeCollectionProgram: Address<TAccountFeeCollectionProgram>;
  signer: TransactionSigner<TAccountSigner>;
  balance: ReportOnFundsInstructionDataArgs['balance'];
};

export function getReportOnFundsInstruction<
  TAccountVault extends string,
  TAccountPolicyProgram extends string,
  TAccountFeeCollectionProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ReportOnFundsInput<
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): ReportOnFundsInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountPolicyProgram,
  TAccountFeeCollectionProgram,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    feeCollectionProgram: {
      value: input.feeCollectionProgram ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.feeCollectionProgram),
      getAccountMeta(accounts.signer),
    ],
    data: getReportOnFundsInstructionDataEncoder().encode(
      args as ReportOnFundsInstructionDataArgs
    ),
    programAddress,
  } as ReportOnFundsInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner
  >);
}

export type ParsedReportOnFundsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    policyProgram: TAccountMetas[1];
    feeCollectionProgram: TAccountMetas[2];
    signer: TAccountMetas[3];
  };
  data: ReportOnFundsInstructionData;
};

export function parseReportOnFundsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedReportOnFundsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      policyProgram: getNextAccount(),
      feeCollectionProgram: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getReportOnFundsInstructionDataDecoder().decode(instruction.data),
  };
}
