/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const RETURN_FUNDS_DISCRIMINATOR = new Uint8Array([
  220, 104, 119, 202, 186, 1, 45, 90,
]);

export function getReturnFundsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RETURN_FUNDS_DISCRIMINATOR,
  );
}

export type ReturnFundsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountShareSignerPda extends string | AccountMeta<string> = string,
  TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountAuthorityTokenAccount extends string | AccountMeta<string> = string,
  TAccountUnderlyingMint extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPolicyProgram extends string | AccountMeta<string> = string,
  TAccountFeeCollectionProgram extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountShareSignerPda extends string
        ? ReadonlyAccount<TAccountShareSignerPda>
        : TAccountShareSignerPda,
      TAccountVaultTokenAccount extends string
        ? WritableAccount<TAccountVaultTokenAccount>
        : TAccountVaultTokenAccount,
      TAccountAuthority extends string
        ? ReadonlyAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountAuthorityTokenAccount extends string
        ? WritableAccount<TAccountAuthorityTokenAccount>
        : TAccountAuthorityTokenAccount,
      TAccountUnderlyingMint extends string
        ? WritableAccount<TAccountUnderlyingMint>
        : TAccountUnderlyingMint,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountPolicyProgram extends string
        ? ReadonlyAccount<TAccountPolicyProgram>
        : TAccountPolicyProgram,
      TAccountFeeCollectionProgram extends string
        ? ReadonlyAccount<TAccountFeeCollectionProgram>
        : TAccountFeeCollectionProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ReturnFundsInstructionData = {
  discriminator: ReadonlyUint8Array;
  assets: bigint;
};

export type ReturnFundsInstructionDataArgs = { assets: number | bigint };

export function getReturnFundsInstructionDataEncoder(): FixedSizeEncoder<ReturnFundsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["assets", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: RETURN_FUNDS_DISCRIMINATOR }),
  );
}

export function getReturnFundsInstructionDataDecoder(): FixedSizeDecoder<ReturnFundsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["assets", getU64Decoder()],
  ]);
}

export function getReturnFundsInstructionDataCodec(): FixedSizeCodec<
  ReturnFundsInstructionDataArgs,
  ReturnFundsInstructionData
> {
  return combineCodec(
    getReturnFundsInstructionDataEncoder(),
    getReturnFundsInstructionDataDecoder(),
  );
}

export type ReturnFundsAsyncInput<
  TAccountShareSignerPda extends string = string,
  TAccountVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountAuthorityTokenAccount extends string = string,
  TAccountUnderlyingMint extends string = string,
  TAccountVault extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountFeeCollectionProgram extends string = string,
  TAccountSigner extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  shareSignerPda?: Address<TAccountShareSignerPda>;
  vaultTokenAccount?: Address<TAccountVaultTokenAccount>;
  authority?: Address<TAccountAuthority>;
  authorityTokenAccount?: Address<TAccountAuthorityTokenAccount>;
  underlyingMint: Address<TAccountUnderlyingMint>;
  vault: Address<TAccountVault>;
  policyProgram: Address<TAccountPolicyProgram>;
  feeCollectionProgram: Address<TAccountFeeCollectionProgram>;
  signer: TransactionSigner<TAccountSigner>;
  tokenProgram?: Address<TAccountTokenProgram>;
  assets: ReturnFundsInstructionDataArgs["assets"];
};

export async function getReturnFundsInstructionAsync<
  TAccountShareSignerPda extends string,
  TAccountVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountAuthorityTokenAccount extends string,
  TAccountUnderlyingMint extends string,
  TAccountVault extends string,
  TAccountPolicyProgram extends string,
  TAccountFeeCollectionProgram extends string,
  TAccountSigner extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ReturnFundsAsyncInput<
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountAuthority,
    TAccountAuthorityTokenAccount,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ReturnFundsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountAuthority,
    TAccountAuthorityTokenAccount,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    shareSignerPda: { value: input.shareSignerPda ?? null, isWritable: false },
    vaultTokenAccount: {
      value: input.vaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: false },
    authorityTokenAccount: {
      value: input.authorityTokenAccount ?? null,
      isWritable: true,
    },
    underlyingMint: { value: input.underlyingMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    feeCollectionProgram: {
      value: input.feeCollectionProgram ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.shareSignerPda.value) {
    accounts.shareSignerPda.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            118, 97, 117, 108, 116, 95, 115, 104, 97, 114, 101, 95, 115, 105,
            103, 110, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }
  if (!accounts.vaultTokenAccount.value) {
    accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            118, 97, 117, 108, 116, 95, 116, 111, 107, 101, 110, 95, 97, 99, 99,
            111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.underlyingMint.value),
        ),
      ],
    });
  }
  if (!accounts.authority.value) {
    accounts.authority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getAddressEncoder().encode(expectAddress(accounts.vault.value))],
    });
  }
  if (!accounts.authorityTokenAccount.value) {
    accounts.authorityTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 117, 116, 104, 111, 114, 105, 116, 121, 95, 116, 111, 107, 101,
            110, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
        getAddressEncoder().encode(
          expectAddress(accounts.underlyingMint.value),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.shareSignerPda),
      getAccountMeta(accounts.vaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.authorityTokenAccount),
      getAccountMeta(accounts.underlyingMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.feeCollectionProgram),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getReturnFundsInstructionDataEncoder().encode(
      args as ReturnFundsInstructionDataArgs,
    ),
    programAddress,
  } as ReturnFundsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountAuthority,
    TAccountAuthorityTokenAccount,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram
  >);
}

export type ReturnFundsInput<
  TAccountShareSignerPda extends string = string,
  TAccountVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountAuthorityTokenAccount extends string = string,
  TAccountUnderlyingMint extends string = string,
  TAccountVault extends string = string,
  TAccountPolicyProgram extends string = string,
  TAccountFeeCollectionProgram extends string = string,
  TAccountSigner extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  shareSignerPda: Address<TAccountShareSignerPda>;
  vaultTokenAccount: Address<TAccountVaultTokenAccount>;
  authority: Address<TAccountAuthority>;
  authorityTokenAccount: Address<TAccountAuthorityTokenAccount>;
  underlyingMint: Address<TAccountUnderlyingMint>;
  vault: Address<TAccountVault>;
  policyProgram: Address<TAccountPolicyProgram>;
  feeCollectionProgram: Address<TAccountFeeCollectionProgram>;
  signer: TransactionSigner<TAccountSigner>;
  tokenProgram?: Address<TAccountTokenProgram>;
  assets: ReturnFundsInstructionDataArgs["assets"];
};

export function getReturnFundsInstruction<
  TAccountShareSignerPda extends string,
  TAccountVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountAuthorityTokenAccount extends string,
  TAccountUnderlyingMint extends string,
  TAccountVault extends string,
  TAccountPolicyProgram extends string,
  TAccountFeeCollectionProgram extends string,
  TAccountSigner extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: ReturnFundsInput<
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountAuthority,
    TAccountAuthorityTokenAccount,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ReturnFundsInstruction<
  TProgramAddress,
  TAccountShareSignerPda,
  TAccountVaultTokenAccount,
  TAccountAuthority,
  TAccountAuthorityTokenAccount,
  TAccountUnderlyingMint,
  TAccountVault,
  TAccountPolicyProgram,
  TAccountFeeCollectionProgram,
  TAccountSigner,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    shareSignerPda: { value: input.shareSignerPda ?? null, isWritable: false },
    vaultTokenAccount: {
      value: input.vaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: false },
    authorityTokenAccount: {
      value: input.authorityTokenAccount ?? null,
      isWritable: true,
    },
    underlyingMint: { value: input.underlyingMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    policyProgram: { value: input.policyProgram ?? null, isWritable: false },
    feeCollectionProgram: {
      value: input.feeCollectionProgram ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.shareSignerPda),
      getAccountMeta(accounts.vaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.authorityTokenAccount),
      getAccountMeta(accounts.underlyingMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyProgram),
      getAccountMeta(accounts.feeCollectionProgram),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getReturnFundsInstructionDataEncoder().encode(
      args as ReturnFundsInstructionDataArgs,
    ),
    programAddress,
  } as ReturnFundsInstruction<
    TProgramAddress,
    TAccountShareSignerPda,
    TAccountVaultTokenAccount,
    TAccountAuthority,
    TAccountAuthorityTokenAccount,
    TAccountUnderlyingMint,
    TAccountVault,
    TAccountPolicyProgram,
    TAccountFeeCollectionProgram,
    TAccountSigner,
    TAccountTokenProgram
  >);
}

export type ParsedReturnFundsInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    shareSignerPda: TAccountMetas[0];
    vaultTokenAccount: TAccountMetas[1];
    authority: TAccountMetas[2];
    authorityTokenAccount: TAccountMetas[3];
    underlyingMint: TAccountMetas[4];
    vault: TAccountMetas[5];
    policyProgram: TAccountMetas[6];
    feeCollectionProgram: TAccountMetas[7];
    signer: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
  };
  data: ReturnFundsInstructionData;
};

export function parseReturnFundsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedReturnFundsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      shareSignerPda: getNextAccount(),
      vaultTokenAccount: getNextAccount(),
      authority: getNextAccount(),
      authorityTokenAccount: getNextAccount(),
      underlyingMint: getNextAccount(),
      vault: getNextAccount(),
      policyProgram: getNextAccount(),
      feeCollectionProgram: getNextAccount(),
      signer: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getReturnFundsInstructionDataDecoder().decode(instruction.data),
  };
}
