/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getVerificationStatusDecoder,
  getVerificationStatusEncoder,
  type VerificationStatus,
  type VerificationStatusArgs,
} from '../types';

export const VERIFY_MANAGER_DISCRIMINATOR = new Uint8Array([
  61, 121, 49, 235, 68, 94, 106, 30,
]);

export function getVerifyManagerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VERIFY_MANAGER_DISCRIMINATOR
  );
}

export type VerifyManagerInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountManagerProfile extends string | AccountMeta<string> = string,
  TAccountRegistry extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountManagerProfile extends string
        ? WritableAccount<TAccountManagerProfile>
        : TAccountManagerProfile,
      TAccountRegistry extends string
        ? ReadonlyAccount<TAccountRegistry>
        : TAccountRegistry,
      ...TRemainingAccounts,
    ]
  >;

export type VerifyManagerInstructionData = {
  discriminator: ReadonlyUint8Array;
  verificationStatus: VerificationStatus;
};

export type VerifyManagerInstructionDataArgs = {
  verificationStatus: VerificationStatusArgs;
};

export function getVerifyManagerInstructionDataEncoder(): FixedSizeEncoder<VerifyManagerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['verificationStatus', getVerificationStatusEncoder()],
    ]),
    (value) => ({ ...value, discriminator: VERIFY_MANAGER_DISCRIMINATOR })
  );
}

export function getVerifyManagerInstructionDataDecoder(): FixedSizeDecoder<VerifyManagerInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['verificationStatus', getVerificationStatusDecoder()],
  ]);
}

export function getVerifyManagerInstructionDataCodec(): FixedSizeCodec<
  VerifyManagerInstructionDataArgs,
  VerifyManagerInstructionData
> {
  return combineCodec(
    getVerifyManagerInstructionDataEncoder(),
    getVerifyManagerInstructionDataDecoder()
  );
}

export type VerifyManagerInput<
  TAccountAdmin extends string = string,
  TAccountManagerProfile extends string = string,
  TAccountRegistry extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  managerProfile: Address<TAccountManagerProfile>;
  registry: Address<TAccountRegistry>;
  verificationStatus: VerifyManagerInstructionDataArgs['verificationStatus'];
};

export function getVerifyManagerInstruction<
  TAccountAdmin extends string,
  TAccountManagerProfile extends string,
  TAccountRegistry extends string,
  TProgramAddress extends Address = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
>(
  input: VerifyManagerInput<
    TAccountAdmin,
    TAccountManagerProfile,
    TAccountRegistry
  >,
  config?: { programAddress?: TProgramAddress }
): VerifyManagerInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountManagerProfile,
  TAccountRegistry
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? HYRO_PROTOCOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    managerProfile: { value: input.managerProfile ?? null, isWritable: true },
    registry: { value: input.registry ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.managerProfile),
      getAccountMeta(accounts.registry),
    ],
    data: getVerifyManagerInstructionDataEncoder().encode(
      args as VerifyManagerInstructionDataArgs
    ),
    programAddress,
  } as VerifyManagerInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountManagerProfile,
    TAccountRegistry
  >);
}

export type ParsedVerifyManagerInstruction<
  TProgram extends string = typeof HYRO_PROTOCOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    managerProfile: TAccountMetas[1];
    registry: TAccountMetas[2];
  };
  data: VerifyManagerInstructionData;
};

export function parseVerifyManagerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedVerifyManagerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      managerProfile: getNextAccount(),
      registry: getNextAccount(),
    },
    data: getVerifyManagerInstructionDataDecoder().decode(instruction.data),
  };
}
