/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** Fee amounts - tracked per fee type */
export type FeeAmounts = {
  lp: bigint;
  manager: bigint;
  protocol: bigint;
  performance: bigint;
};

export type FeeAmountsArgs = {
  lp: number | bigint;
  manager: number | bigint;
  protocol: number | bigint;
  performance: number | bigint;
};

export function getFeeAmountsEncoder(): FixedSizeEncoder<FeeAmountsArgs> {
  return getStructEncoder([
    ["lp", getU64Encoder()],
    ["manager", getU64Encoder()],
    ["protocol", getU64Encoder()],
    ["performance", getU64Encoder()],
  ]);
}

export function getFeeAmountsDecoder(): FixedSizeDecoder<FeeAmounts> {
  return getStructDecoder([
    ["lp", getU64Decoder()],
    ["manager", getU64Decoder()],
    ["protocol", getU64Decoder()],
    ["performance", getU64Decoder()],
  ]);
}

export function getFeeAmountsCodec(): FixedSizeCodec<
  FeeAmountsArgs,
  FeeAmounts
> {
  return combineCodec(getFeeAmountsEncoder(), getFeeAmountsDecoder());
}
