/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Fee recipients - verified addresses for each fee type */
export type FeeRecipients = {
  lpRecipient: Address;
  managerRecipient: Address;
  protocolRecipient: Address;
  performanceRecipient: Address;
};

export type FeeRecipientsArgs = FeeRecipients;

export function getFeeRecipientsEncoder(): FixedSizeEncoder<FeeRecipientsArgs> {
  return getStructEncoder([
    ['lpRecipient', getAddressEncoder()],
    ['managerRecipient', getAddressEncoder()],
    ['protocolRecipient', getAddressEncoder()],
    ['performanceRecipient', getAddressEncoder()],
  ]);
}

export function getFeeRecipientsDecoder(): FixedSizeDecoder<FeeRecipients> {
  return getStructDecoder([
    ['lpRecipient', getAddressDecoder()],
    ['managerRecipient', getAddressDecoder()],
    ['protocolRecipient', getAddressDecoder()],
    ['performanceRecipient', getAddressDecoder()],
  ]);
}

export function getFeeRecipientsCodec(): FixedSizeCodec<
  FeeRecipientsArgs,
  FeeRecipients
> {
  return combineCodec(getFeeRecipientsEncoder(), getFeeRecipientsDecoder());
}
