/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS } from '../programs';

/** UnregisteredManager: Unregistered manager. */
export const POLICY_MANAGER_ACCESS_ERROR__UNREGISTERED_MANAGER = 0x1770; // 6000
/** InvalidPolicyPda: Invalid policy PDA. */
export const POLICY_MANAGER_ACCESS_ERROR__INVALID_POLICY_PDA = 0x1771; // 6001

export type PolicyManagerAccessError =
  | typeof POLICY_MANAGER_ACCESS_ERROR__INVALID_POLICY_PDA
  | typeof POLICY_MANAGER_ACCESS_ERROR__UNREGISTERED_MANAGER;

let policyManagerAccessErrorMessages:
  | Record<PolicyManagerAccessError, string>
  | undefined;
if (process.env.NODE_ENV !== 'production') {
  policyManagerAccessErrorMessages = {
    [POLICY_MANAGER_ACCESS_ERROR__INVALID_POLICY_PDA]: `Invalid policy PDA.`,
    [POLICY_MANAGER_ACCESS_ERROR__UNREGISTERED_MANAGER]: `Unregistered manager.`,
  };
}

export function getPolicyManagerAccessErrorMessage(
  code: PolicyManagerAccessError
): string {
  if (process.env.NODE_ENV !== 'production') {
    return (
      policyManagerAccessErrorMessages as Record<
        PolicyManagerAccessError,
        string
      >
    )[code];
  }

  return 'Error message not available in production bundles.';
}

export function isPolicyManagerAccessError<
  TProgramErrorCode extends PolicyManagerAccessError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS,
    code
  );
}
