/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { FEE_COLLECTION_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const GET_TOTAL_UNCLAIMED_FEES_DISCRIMINATOR = new Uint8Array([
  42, 90, 205, 36, 10, 78, 126, 72,
]);

export function getGetTotalUnclaimedFeesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_TOTAL_UNCLAIMED_FEES_DISCRIMINATOR
  );
}

export type GetTotalUnclaimedFeesInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountVaultFees extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultFees extends string
        ? ReadonlyAccount<TAccountVaultFees>
        : TAccountVaultFees,
      ...TRemainingAccounts,
    ]
  >;

export type GetTotalUnclaimedFeesInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GetTotalUnclaimedFeesInstructionDataArgs = {};

export function getGetTotalUnclaimedFeesInstructionDataEncoder(): FixedSizeEncoder<GetTotalUnclaimedFeesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: GET_TOTAL_UNCLAIMED_FEES_DISCRIMINATOR,
    })
  );
}

export function getGetTotalUnclaimedFeesInstructionDataDecoder(): FixedSizeDecoder<GetTotalUnclaimedFeesInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetTotalUnclaimedFeesInstructionDataCodec(): FixedSizeCodec<
  GetTotalUnclaimedFeesInstructionDataArgs,
  GetTotalUnclaimedFeesInstructionData
> {
  return combineCodec(
    getGetTotalUnclaimedFeesInstructionDataEncoder(),
    getGetTotalUnclaimedFeesInstructionDataDecoder()
  );
}

export type GetTotalUnclaimedFeesAsyncInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees?: Address<TAccountVaultFees>;
};

export async function getGetTotalUnclaimedFeesInstructionAsync<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: GetTotalUnclaimedFeesAsyncInput<TAccountVault, TAccountVaultFees>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  GetTotalUnclaimedFeesInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.vaultFees.value) {
    accounts.vaultFees.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([118, 97, 117, 108, 116, 95, 102, 101, 101, 115])
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
    ],
    data: getGetTotalUnclaimedFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as GetTotalUnclaimedFeesInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees
  >);
}

export type GetTotalUnclaimedFeesInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees: Address<TAccountVaultFees>;
};

export function getGetTotalUnclaimedFeesInstruction<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: GetTotalUnclaimedFeesInput<TAccountVault, TAccountVaultFees>,
  config?: { programAddress?: TProgramAddress }
): GetTotalUnclaimedFeesInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountVaultFees
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
    ],
    data: getGetTotalUnclaimedFeesInstructionDataEncoder().encode({}),
    programAddress,
  } as GetTotalUnclaimedFeesInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees
  >);
}

export type ParsedGetTotalUnclaimedFeesInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    vaultFees: TAccountMetas[1];
  };
  data: GetTotalUnclaimedFeesInstructionData;
};

export function parseGetTotalUnclaimedFeesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGetTotalUnclaimedFeesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { vault: getNextAccount(), vaultFees: getNextAccount() },
    data: getGetTotalUnclaimedFeesInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
