/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { FEE_COLLECTION_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getFeeTypeDecoder,
  getFeeTypeEncoder,
  type FeeType,
  type FeeTypeArgs,
} from "../types";

export const GET_UNCLAIMED_FEES_DISCRIMINATOR = new Uint8Array([
  245, 106, 131, 106, 119, 180, 24, 222,
]);

export function getGetUnclaimedFeesDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_UNCLAIMED_FEES_DISCRIMINATOR,
  );
}

export type GetUnclaimedFeesInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountVaultFees extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultFees extends string
        ? ReadonlyAccount<TAccountVaultFees>
        : TAccountVaultFees,
      ...TRemainingAccounts,
    ]
  >;

export type GetUnclaimedFeesInstructionData = {
  discriminator: ReadonlyUint8Array;
  feeType: FeeType;
};

export type GetUnclaimedFeesInstructionDataArgs = { feeType: FeeTypeArgs };

export function getGetUnclaimedFeesInstructionDataEncoder(): FixedSizeEncoder<GetUnclaimedFeesInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["feeType", getFeeTypeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: GET_UNCLAIMED_FEES_DISCRIMINATOR }),
  );
}

export function getGetUnclaimedFeesInstructionDataDecoder(): FixedSizeDecoder<GetUnclaimedFeesInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["feeType", getFeeTypeDecoder()],
  ]);
}

export function getGetUnclaimedFeesInstructionDataCodec(): FixedSizeCodec<
  GetUnclaimedFeesInstructionDataArgs,
  GetUnclaimedFeesInstructionData
> {
  return combineCodec(
    getGetUnclaimedFeesInstructionDataEncoder(),
    getGetUnclaimedFeesInstructionDataDecoder(),
  );
}

export type GetUnclaimedFeesAsyncInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees?: Address<TAccountVaultFees>;
  feeType: GetUnclaimedFeesInstructionDataArgs["feeType"];
};

export async function getGetUnclaimedFeesInstructionAsync<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: GetUnclaimedFeesAsyncInput<TAccountVault, TAccountVaultFees>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  GetUnclaimedFeesInstruction<TProgramAddress, TAccountVault, TAccountVaultFees>
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.vaultFees.value) {
    accounts.vaultFees.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([118, 97, 117, 108, 116, 95, 102, 101, 101, 115]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
    ],
    data: getGetUnclaimedFeesInstructionDataEncoder().encode(
      args as GetUnclaimedFeesInstructionDataArgs,
    ),
    programAddress,
  } as GetUnclaimedFeesInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees
  >);
}

export type GetUnclaimedFeesInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees: Address<TAccountVaultFees>;
  feeType: GetUnclaimedFeesInstructionDataArgs["feeType"];
};

export function getGetUnclaimedFeesInstruction<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: GetUnclaimedFeesInput<TAccountVault, TAccountVaultFees>,
  config?: { programAddress?: TProgramAddress },
): GetUnclaimedFeesInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountVaultFees
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
    ],
    data: getGetUnclaimedFeesInstructionDataEncoder().encode(
      args as GetUnclaimedFeesInstructionDataArgs,
    ),
    programAddress,
  } as GetUnclaimedFeesInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees
  >);
}

export type ParsedGetUnclaimedFeesInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    vaultFees: TAccountMetas[1];
  };
  data: GetUnclaimedFeesInstructionData;
};

export function parseGetUnclaimedFeesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGetUnclaimedFeesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { vault: getNextAccount(), vaultFees: getNextAccount() },
    data: getGetUnclaimedFeesInstructionDataDecoder().decode(instruction.data),
  };
}
