/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { FEE_COLLECTION_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const SET_FEE_CALC_PROGRAM_DISCRIMINATOR = new Uint8Array([
  147, 88, 46, 194, 190, 141, 216, 84,
]);

export function getSetFeeCalcProgramDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_FEE_CALC_PROGRAM_DISCRIMINATOR
  );
}

export type SetFeeCalcProgramInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountVaultFees extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultFees extends string
        ? WritableAccount<TAccountVaultFees>
        : TAccountVaultFees,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SetFeeCalcProgramInstructionData = {
  discriminator: ReadonlyUint8Array;
  program: Address;
};

export type SetFeeCalcProgramInstructionDataArgs = { program: Address };

export function getSetFeeCalcProgramInstructionDataEncoder(): FixedSizeEncoder<SetFeeCalcProgramInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['program', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_FEE_CALC_PROGRAM_DISCRIMINATOR })
  );
}

export function getSetFeeCalcProgramInstructionDataDecoder(): FixedSizeDecoder<SetFeeCalcProgramInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['program', getAddressDecoder()],
  ]);
}

export function getSetFeeCalcProgramInstructionDataCodec(): FixedSizeCodec<
  SetFeeCalcProgramInstructionDataArgs,
  SetFeeCalcProgramInstructionData
> {
  return combineCodec(
    getSetFeeCalcProgramInstructionDataEncoder(),
    getSetFeeCalcProgramInstructionDataDecoder()
  );
}

export type SetFeeCalcProgramAsyncInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
  TAccountAuthority extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees?: Address<TAccountVaultFees>;
  /** Authority that can set fee calc program */
  authority: TransactionSigner<TAccountAuthority>;
  program: SetFeeCalcProgramInstructionDataArgs['program'];
};

export async function getSetFeeCalcProgramInstructionAsync<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: SetFeeCalcProgramAsyncInput<
    TAccountVault,
    TAccountVaultFees,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  SetFeeCalcProgramInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.vaultFees.value) {
    accounts.vaultFees.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([118, 97, 117, 108, 116, 95, 102, 101, 101, 115])
        ),
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
      getAccountMeta(accounts.authority),
    ],
    data: getSetFeeCalcProgramInstructionDataEncoder().encode(
      args as SetFeeCalcProgramInstructionDataArgs
    ),
    programAddress,
  } as SetFeeCalcProgramInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees,
    TAccountAuthority
  >);
}

export type SetFeeCalcProgramInput<
  TAccountVault extends string = string,
  TAccountVaultFees extends string = string,
  TAccountAuthority extends string = string,
> = {
  vault: Address<TAccountVault>;
  vaultFees: Address<TAccountVaultFees>;
  /** Authority that can set fee calc program */
  authority: TransactionSigner<TAccountAuthority>;
  program: SetFeeCalcProgramInstructionDataArgs['program'];
};

export function getSetFeeCalcProgramInstruction<
  TAccountVault extends string,
  TAccountVaultFees extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
>(
  input: SetFeeCalcProgramInput<
    TAccountVault,
    TAccountVaultFees,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): SetFeeCalcProgramInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountVaultFees,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? FEE_COLLECTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    vaultFees: { value: input.vaultFees ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultFees),
      getAccountMeta(accounts.authority),
    ],
    data: getSetFeeCalcProgramInstructionDataEncoder().encode(
      args as SetFeeCalcProgramInstructionDataArgs
    ),
    programAddress,
  } as SetFeeCalcProgramInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountVaultFees,
    TAccountAuthority
  >);
}

export type ParsedSetFeeCalcProgramInstruction<
  TProgram extends string = typeof FEE_COLLECTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    vaultFees: TAccountMetas[1];
    /** Authority that can set fee calc program */
    authority: TAccountMetas[2];
  };
  data: SetFeeCalcProgramInstructionData;
};

export function parseSetFeeCalcProgramInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetFeeCalcProgramInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      vaultFees: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getSetFeeCalcProgramInstructionDataDecoder().decode(instruction.data),
  };
}
