/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedChargeFeesCpiInstruction,
  type ParsedClaimFeesInstruction,
  type ParsedGetTotalUnclaimedFeesInstruction,
  type ParsedGetUnclaimedFeesInstruction,
  type ParsedInitializeInstruction,
  type ParsedSetFeeCalcProgramInstruction,
  type ParsedUpdateHighWaterMarkInstruction,
  type ParsedUpdateRecipientsInstruction,
} from '../instructions';

export const FEE_COLLECTION_PROGRAM_ADDRESS =
  'Hyro1e6sqYJEGvwy6Yszq5JZXL6KcR5fLQC4dYq7UU96' as Address<'Hyro1e6sqYJEGvwy6Yszq5JZXL6KcR5fLQC4dYq7UU96'>;

export enum FeeCollectionAccount {
  VaultFees,
}

export function identifyFeeCollectionAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): FeeCollectionAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([160, 42, 52, 120, 52, 123, 127, 118])
      ),
      0
    )
  ) {
    return FeeCollectionAccount.VaultFees;
  }
  throw new Error(
    'The provided account could not be identified as a feeCollection account.'
  );
}

export enum FeeCollectionInstruction {
  ChargeFeesCpi,
  ClaimFees,
  GetTotalUnclaimedFees,
  GetUnclaimedFees,
  Initialize,
  SetFeeCalcProgram,
  UpdateHighWaterMark,
  UpdateRecipients,
}

export function identifyFeeCollectionInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): FeeCollectionInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 58, 69, 9, 245, 105, 154, 0])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.ChargeFeesCpi;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([82, 251, 233, 156, 12, 52, 184, 202])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.ClaimFees;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([42, 90, 205, 36, 10, 78, 126, 72])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.GetTotalUnclaimedFees;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([245, 106, 131, 106, 119, 180, 24, 222])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.GetUnclaimedFees;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([147, 88, 46, 194, 190, 141, 216, 84])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.SetFeeCalcProgram;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([68, 148, 239, 216, 150, 14, 205, 238])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.UpdateHighWaterMark;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([92, 134, 20, 47, 48, 34, 175, 112])
      ),
      0
    )
  ) {
    return FeeCollectionInstruction.UpdateRecipients;
  }
  throw new Error(
    'The provided instruction could not be identified as a feeCollection instruction.'
  );
}

export type ParsedFeeCollectionInstruction<
  TProgram extends string = 'Hyro1e6sqYJEGvwy6Yszq5JZXL6KcR5fLQC4dYq7UU96',
> =
  | ({
      instructionType: FeeCollectionInstruction.ChargeFeesCpi;
    } & ParsedChargeFeesCpiInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.ClaimFees;
    } & ParsedClaimFeesInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.GetTotalUnclaimedFees;
    } & ParsedGetTotalUnclaimedFeesInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.GetUnclaimedFees;
    } & ParsedGetUnclaimedFeesInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.SetFeeCalcProgram;
    } & ParsedSetFeeCalcProgramInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.UpdateHighWaterMark;
    } & ParsedUpdateHighWaterMarkInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionInstruction.UpdateRecipients;
    } & ParsedUpdateRecipientsInstruction<TProgram>);
