/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { POLICY_OWNERS_PROGRAM_ADDRESS } from "../programs";

/** UnauthorizedSender: Unauthorized sender. */
export const POLICY_OWNERS_ERROR__UNAUTHORIZED_SENDER = 0x1770; // 6000
/** InvalidPolicyPda: Invalid policy PDA. */
export const POLICY_OWNERS_ERROR__INVALID_POLICY_PDA = 0x1771; // 6001

export type PolicyOwnersError =
  | typeof POLICY_OWNERS_ERROR__INVALID_POLICY_PDA
  | typeof POLICY_OWNERS_ERROR__UNAUTHORIZED_SENDER;

let policyOwnersErrorMessages: Record<PolicyOwnersError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  policyOwnersErrorMessages = {
    [POLICY_OWNERS_ERROR__INVALID_POLICY_PDA]: `Invalid policy PDA.`,
    [POLICY_OWNERS_ERROR__UNAUTHORIZED_SENDER]: `Unauthorized sender.`,
  };
}

export function getPolicyOwnersErrorMessage(code: PolicyOwnersError): string {
  if (process.env.NODE_ENV !== "production") {
    return (policyOwnersErrorMessages as Record<PolicyOwnersError, string>)[
      code
    ];
  }

  return "Error message not available in production bundles.";
}

export function isPolicyOwnersError<
  TProgramErrorCode extends PolicyOwnersError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    POLICY_OWNERS_PROGRAM_ADDRESS,
    code,
  );
}
