/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getRiskRatingDecoder,
  getRiskRatingEncoder,
  getVerificationStatusDecoder,
  getVerificationStatusEncoder,
  type RiskRating,
  type RiskRatingArgs,
  type VerificationStatus,
  type VerificationStatusArgs,
} from "../types";

export const MANAGER_PROFILE_DISCRIMINATOR = new Uint8Array([
  135, 12, 238, 243, 236, 32, 123, 52,
]);

export function getManagerProfileDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MANAGER_PROFILE_DISCRIMINATOR,
  );
}

export type ManagerProfile = {
  discriminator: ReadonlyUint8Array;
  managerPubkey: Address;
  verificationStatus: VerificationStatus;
  riskRating: RiskRating;
  totalAum: bigint;
  activeVaults: number;
  totalFeesEarned: bigint;
  createdAt: bigint;
  lastActivity: bigint;
};

export type ManagerProfileArgs = {
  managerPubkey: Address;
  verificationStatus: VerificationStatusArgs;
  riskRating: RiskRatingArgs;
  totalAum: number | bigint;
  activeVaults: number;
  totalFeesEarned: number | bigint;
  createdAt: number | bigint;
  lastActivity: number | bigint;
};

/** Gets the encoder for {@link ManagerProfileArgs} account data. */
export function getManagerProfileEncoder(): FixedSizeEncoder<ManagerProfileArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["managerPubkey", getAddressEncoder()],
      ["verificationStatus", getVerificationStatusEncoder()],
      ["riskRating", getRiskRatingEncoder()],
      ["totalAum", getU64Encoder()],
      ["activeVaults", getU32Encoder()],
      ["totalFeesEarned", getU64Encoder()],
      ["createdAt", getU64Encoder()],
      ["lastActivity", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MANAGER_PROFILE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link ManagerProfile} account data. */
export function getManagerProfileDecoder(): FixedSizeDecoder<ManagerProfile> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["managerPubkey", getAddressDecoder()],
    ["verificationStatus", getVerificationStatusDecoder()],
    ["riskRating", getRiskRatingDecoder()],
    ["totalAum", getU64Decoder()],
    ["activeVaults", getU32Decoder()],
    ["totalFeesEarned", getU64Decoder()],
    ["createdAt", getU64Decoder()],
    ["lastActivity", getU64Decoder()],
  ]);
}

/** Gets the codec for {@link ManagerProfile} account data. */
export function getManagerProfileCodec(): FixedSizeCodec<
  ManagerProfileArgs,
  ManagerProfile
> {
  return combineCodec(getManagerProfileEncoder(), getManagerProfileDecoder());
}

export function decodeManagerProfile<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<ManagerProfile, TAddress>;
export function decodeManagerProfile<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<ManagerProfile, TAddress>;
export function decodeManagerProfile<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<ManagerProfile, TAddress> | MaybeAccount<ManagerProfile, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getManagerProfileDecoder(),
  );
}

export async function fetchManagerProfile<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<ManagerProfile, TAddress>> {
  const maybeAccount = await fetchMaybeManagerProfile(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeManagerProfile<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<ManagerProfile, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeManagerProfile(maybeAccount);
}

export async function fetchAllManagerProfile(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<ManagerProfile>[]> {
  const maybeAccounts = await fetchAllMaybeManagerProfile(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeManagerProfile(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<ManagerProfile>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeManagerProfile(maybeAccount),
  );
}

export function getManagerProfileSize(): number {
  return 78;
}
