/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const MANAGER_REGISTRY_DISCRIMINATOR = new Uint8Array([
  181, 78, 54, 100, 122, 86, 63, 114,
]);

export function getManagerRegistryDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MANAGER_REGISTRY_DISCRIMINATOR
  );
}

export type ManagerRegistry = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  totalManagers: number;
  totalAum: bigint;
  createdAt: bigint;
};

export type ManagerRegistryArgs = {
  admin: Address;
  totalManagers: number;
  totalAum: number | bigint;
  createdAt: number | bigint;
};

/** Gets the encoder for {@link ManagerRegistryArgs} account data. */
export function getManagerRegistryEncoder(): FixedSizeEncoder<ManagerRegistryArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['admin', getAddressEncoder()],
      ['totalManagers', getU32Encoder()],
      ['totalAum', getU64Encoder()],
      ['createdAt', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MANAGER_REGISTRY_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link ManagerRegistry} account data. */
export function getManagerRegistryDecoder(): FixedSizeDecoder<ManagerRegistry> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['admin', getAddressDecoder()],
    ['totalManagers', getU32Decoder()],
    ['totalAum', getU64Decoder()],
    ['createdAt', getU64Decoder()],
  ]);
}

/** Gets the codec for {@link ManagerRegistry} account data. */
export function getManagerRegistryCodec(): FixedSizeCodec<
  ManagerRegistryArgs,
  ManagerRegistry
> {
  return combineCodec(getManagerRegistryEncoder(), getManagerRegistryDecoder());
}

export function decodeManagerRegistry<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<ManagerRegistry, TAddress>;
export function decodeManagerRegistry<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ManagerRegistry, TAddress>;
export function decodeManagerRegistry<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<ManagerRegistry, TAddress>
  | MaybeAccount<ManagerRegistry, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getManagerRegistryDecoder()
  );
}

export async function fetchManagerRegistry<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<ManagerRegistry, TAddress>> {
  const maybeAccount = await fetchMaybeManagerRegistry(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeManagerRegistry<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<ManagerRegistry, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeManagerRegistry(maybeAccount);
}

export async function fetchAllManagerRegistry(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<ManagerRegistry>[]> {
  const maybeAccounts = await fetchAllMaybeManagerRegistry(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeManagerRegistry(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<ManagerRegistry>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeManagerRegistry(maybeAccount)
  );
}

export function getManagerRegistrySize(): number {
  return 60;
}
