/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const LIMIT_TRANSFER_DISCRIMINATOR = new Uint8Array([
  247, 207, 59, 55, 224, 191, 85, 213,
]);

export function getLimitTransferDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    LIMIT_TRANSFER_DISCRIMINATOR
  );
}

export type LimitTransfer = {
  discriminator: ReadonlyUint8Array;
  max: bigint;
  min: bigint;
};

export type LimitTransferArgs = { max: number | bigint; min: number | bigint };

/** Gets the encoder for {@link LimitTransferArgs} account data. */
export function getLimitTransferEncoder(): FixedSizeEncoder<LimitTransferArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['max', getU64Encoder()],
      ['min', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: LIMIT_TRANSFER_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link LimitTransfer} account data. */
export function getLimitTransferDecoder(): FixedSizeDecoder<LimitTransfer> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['max', getU64Decoder()],
    ['min', getU64Decoder()],
  ]);
}

/** Gets the codec for {@link LimitTransfer} account data. */
export function getLimitTransferCodec(): FixedSizeCodec<
  LimitTransferArgs,
  LimitTransfer
> {
  return combineCodec(getLimitTransferEncoder(), getLimitTransferDecoder());
}

export function decodeLimitTransfer<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<LimitTransfer, TAddress>;
export function decodeLimitTransfer<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<LimitTransfer, TAddress>;
export function decodeLimitTransfer<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<LimitTransfer, TAddress> | MaybeAccount<LimitTransfer, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getLimitTransferDecoder()
  );
}

export async function fetchLimitTransfer<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<LimitTransfer, TAddress>> {
  const maybeAccount = await fetchMaybeLimitTransfer(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeLimitTransfer<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<LimitTransfer, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeLimitTransfer(maybeAccount);
}

export async function fetchAllLimitTransfer(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<LimitTransfer>[]> {
  const maybeAccounts = await fetchAllMaybeLimitTransfer(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeLimitTransfer(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<LimitTransfer>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeLimitTransfer(maybeAccount));
}

export function getLimitTransferSize(): number {
  return 24;
}
