/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getPercentDecoder,
  getPercentEncoder,
  getSmallScalarDecoder,
  getSmallScalarEncoder,
  getStageTypeDecoder,
  getStageTypeEncoder,
  type Percent,
  type PercentArgs,
  type SmallScalar,
  type SmallScalarArgs,
  type StageType,
  type StageTypeArgs,
} from ".";

export type ChallengeTemplateUpdateInsertDto = {
  stageSequence: number;
  stageType: StageType;
  startingDeposit: bigint;
  admin: Address;
  entranceCost: bigint;
  entranceTokenMint: Address;
  minimumTradingDays: SmallScalar;
  dailyDrawdown: Percent;
  maximumLoss: Percent;
  profitTarget: Percent;
  maxParticipants: SmallScalar;
  isActive: boolean;
};

export type ChallengeTemplateUpdateInsertDtoArgs = {
  stageSequence: number;
  stageType: StageTypeArgs;
  startingDeposit: number | bigint;
  admin: Address;
  entranceCost: number | bigint;
  entranceTokenMint: Address;
  minimumTradingDays: SmallScalarArgs;
  dailyDrawdown: PercentArgs;
  maximumLoss: PercentArgs;
  profitTarget: PercentArgs;
  maxParticipants: SmallScalarArgs;
  isActive: boolean;
};

export function getChallengeTemplateUpdateInsertDtoEncoder(): FixedSizeEncoder<ChallengeTemplateUpdateInsertDtoArgs> {
  return getStructEncoder([
    ["stageSequence", getU8Encoder()],
    ["stageType", getStageTypeEncoder()],
    ["startingDeposit", getU64Encoder()],
    ["admin", getAddressEncoder()],
    ["entranceCost", getU64Encoder()],
    ["entranceTokenMint", getAddressEncoder()],
    ["minimumTradingDays", getSmallScalarEncoder()],
    ["dailyDrawdown", getPercentEncoder()],
    ["maximumLoss", getPercentEncoder()],
    ["profitTarget", getPercentEncoder()],
    ["maxParticipants", getSmallScalarEncoder()],
    ["isActive", getBooleanEncoder()],
  ]);
}

export function getChallengeTemplateUpdateInsertDtoDecoder(): FixedSizeDecoder<ChallengeTemplateUpdateInsertDto> {
  return getStructDecoder([
    ["stageSequence", getU8Decoder()],
    ["stageType", getStageTypeDecoder()],
    ["startingDeposit", getU64Decoder()],
    ["admin", getAddressDecoder()],
    ["entranceCost", getU64Decoder()],
    ["entranceTokenMint", getAddressDecoder()],
    ["minimumTradingDays", getSmallScalarDecoder()],
    ["dailyDrawdown", getPercentDecoder()],
    ["maximumLoss", getPercentDecoder()],
    ["profitTarget", getPercentDecoder()],
    ["maxParticipants", getSmallScalarDecoder()],
    ["isActive", getBooleanDecoder()],
  ]);
}

export function getChallengeTemplateUpdateInsertDtoCodec(): FixedSizeCodec<
  ChallengeTemplateUpdateInsertDtoArgs,
  ChallengeTemplateUpdateInsertDto
> {
  return combineCodec(
    getChallengeTemplateUpdateInsertDtoEncoder(),
    getChallengeTemplateUpdateInsertDtoDecoder(),
  );
}
