/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getAmountDecoder,
  getAmountEncoder,
  getPercentDecoder,
  getPercentEncoder,
  type Amount,
  type AmountArgs,
  type Percent,
  type PercentArgs,
} from ".";

export type MaximumLoss = {
  maximumLossPercentage: Percent;
  maximumLossAmount: Amount;
  currentLossAchieved: Percent;
  currentLossAchievedAmount: Amount;
};

export type MaximumLossArgs = {
  maximumLossPercentage: PercentArgs;
  maximumLossAmount: AmountArgs;
  currentLossAchieved: PercentArgs;
  currentLossAchievedAmount: AmountArgs;
};

export function getMaximumLossEncoder(): FixedSizeEncoder<MaximumLossArgs> {
  return getStructEncoder([
    ["maximumLossPercentage", getPercentEncoder()],
    ["maximumLossAmount", getAmountEncoder()],
    ["currentLossAchieved", getPercentEncoder()],
    ["currentLossAchievedAmount", getAmountEncoder()],
  ]);
}

export function getMaximumLossDecoder(): FixedSizeDecoder<MaximumLoss> {
  return getStructDecoder([
    ["maximumLossPercentage", getPercentDecoder()],
    ["maximumLossAmount", getAmountDecoder()],
    ["currentLossAchieved", getPercentDecoder()],
    ["currentLossAchievedAmount", getAmountDecoder()],
  ]);
}

export function getMaximumLossCodec(): FixedSizeCodec<
  MaximumLossArgs,
  MaximumLoss
> {
  return combineCodec(getMaximumLossEncoder(), getMaximumLossDecoder());
}
