/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI16Decoder,
  getI16Encoder,
  getTupleDecoder,
  getTupleEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Percent = readonly [number];

export type PercentArgs = Percent;

export function getPercentEncoder(): FixedSizeEncoder<PercentArgs> {
  return getTupleEncoder([getI16Encoder()]);
}

export function getPercentDecoder(): FixedSizeDecoder<Percent> {
  return getTupleDecoder([getI16Decoder()]);
}

export function getPercentCodec(): FixedSizeCodec<PercentArgs, Percent> {
  return combineCodec(getPercentEncoder(), getPercentDecoder());
}
