/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getSmallScalarDecoder,
  getSmallScalarEncoder,
  type SmallScalar,
  type SmallScalarArgs,
} from ".";

export type TradingDays = {
  required: SmallScalar;
  completed: SmallScalar;
  requirementsMet: boolean;
  remainingDays: SmallScalar;
};

export type TradingDaysArgs = {
  required: SmallScalarArgs;
  completed: SmallScalarArgs;
  requirementsMet: boolean;
  remainingDays: SmallScalarArgs;
};

export function getTradingDaysEncoder(): FixedSizeEncoder<TradingDaysArgs> {
  return getStructEncoder([
    ["required", getSmallScalarEncoder()],
    ["completed", getSmallScalarEncoder()],
    ["requirementsMet", getBooleanEncoder()],
    ["remainingDays", getSmallScalarEncoder()],
  ]);
}

export function getTradingDaysDecoder(): FixedSizeDecoder<TradingDays> {
  return getStructDecoder([
    ["required", getSmallScalarDecoder()],
    ["completed", getSmallScalarDecoder()],
    ["requirementsMet", getBooleanDecoder()],
    ["remainingDays", getSmallScalarDecoder()],
  ]);
}

export function getTradingDaysCodec(): FixedSizeCodec<
  TradingDaysArgs,
  TradingDays
> {
  return combineCodec(getTradingDaysEncoder(), getTradingDaysDecoder());
}
