/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseCalculateFeesInstruction,
  parseInitializeInstruction,
  parseResetTimestampsInstruction,
  parseUpdateConfigInstruction,
  type ParsedCalculateFeesInstruction,
  type ParsedInitializeInstruction,
  type ParsedResetTimestampsInstruction,
  type ParsedUpdateConfigInstruction,
} from "../instructions";

export const FEE_COLLECTION_TIME_BASED_PROGRAM_ADDRESS =
  "EGGcosshV6LQU4DSnCSv2GCtuukhEoi2QECsaM51L28S" as Address<"EGGcosshV6LQU4DSnCSv2GCtuukhEoi2QECsaM51L28S">;

export enum FeeCollectionTimeBasedAccount {
  VaultTimeBasedConfig,
}

export function identifyFeeCollectionTimeBasedAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): FeeCollectionTimeBasedAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([37, 247, 4, 179, 149, 79, 143, 246]),
      ),
      0,
    )
  ) {
    return FeeCollectionTimeBasedAccount.VaultTimeBasedConfig;
  }
  throw new Error(
    "The provided account could not be identified as a feeCollectionTimeBased account.",
  );
}

export enum FeeCollectionTimeBasedInstruction {
  CalculateFees,
  Initialize,
  ResetTimestamps,
  UpdateConfig,
}

export function identifyFeeCollectionTimeBasedInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): FeeCollectionTimeBasedInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([140, 235, 78, 9, 249, 8, 129, 101]),
      ),
      0,
    )
  ) {
    return FeeCollectionTimeBasedInstruction.CalculateFees;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return FeeCollectionTimeBasedInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([145, 21, 122, 247, 201, 112, 88, 236]),
      ),
      0,
    )
  ) {
    return FeeCollectionTimeBasedInstruction.ResetTimestamps;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([29, 158, 252, 191, 10, 83, 219, 99]),
      ),
      0,
    )
  ) {
    return FeeCollectionTimeBasedInstruction.UpdateConfig;
  }
  throw new Error(
    "The provided instruction could not be identified as a feeCollectionTimeBased instruction.",
  );
}

export type ParsedFeeCollectionTimeBasedInstruction<
  TProgram extends string = "EGGcosshV6LQU4DSnCSv2GCtuukhEoi2QECsaM51L28S",
> =
  | ({
      instructionType: FeeCollectionTimeBasedInstruction.CalculateFees;
    } & ParsedCalculateFeesInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionTimeBasedInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionTimeBasedInstruction.ResetTimestamps;
    } & ParsedResetTimestampsInstruction<TProgram>)
  | ({
      instructionType: FeeCollectionTimeBasedInstruction.UpdateConfig;
    } & ParsedUpdateConfigInstruction<TProgram>);

export function parseFeeCollectionTimeBasedInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedFeeCollectionTimeBasedInstruction<TProgram> {
  const instructionType =
    identifyFeeCollectionTimeBasedInstruction(instruction);
  switch (instructionType) {
    case FeeCollectionTimeBasedInstruction.CalculateFees: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: FeeCollectionTimeBasedInstruction.CalculateFees,
        ...parseCalculateFeesInstruction(instruction),
      };
    }
    case FeeCollectionTimeBasedInstruction.Initialize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: FeeCollectionTimeBasedInstruction.Initialize,
        ...parseInitializeInstruction(instruction),
      };
    }
    case FeeCollectionTimeBasedInstruction.ResetTimestamps: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: FeeCollectionTimeBasedInstruction.ResetTimestamps,
        ...parseResetTimestampsInstruction(instruction),
      };
    }
    case FeeCollectionTimeBasedInstruction.UpdateConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: FeeCollectionTimeBasedInstruction.UpdateConfig,
        ...parseUpdateConfigInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
