/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INITIALIZE_MANAGERS_DISCRIMINATOR = new Uint8Array([
  184, 12, 75, 43, 10, 73, 29, 155,
]);

export function getInitializeManagersDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_MANAGERS_DISCRIMINATOR,
  );
}

export type InitializeManagersInstruction<
  TProgram extends string = typeof POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPolicyAccount extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountPolicyAccount extends string
        ? WritableAccount<TAccountPolicyAccount>
        : TAccountPolicyAccount,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeManagersInstructionData = {
  discriminator: ReadonlyUint8Array;
  managers: Array<Address>;
};

export type InitializeManagersInstructionDataArgs = {
  managers: Array<Address>;
};

export function getInitializeManagersInstructionDataEncoder(): Encoder<InitializeManagersInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["managers", getArrayEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_MANAGERS_DISCRIMINATOR }),
  );
}

export function getInitializeManagersInstructionDataDecoder(): Decoder<InitializeManagersInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["managers", getArrayDecoder(getAddressDecoder())],
  ]);
}

export function getInitializeManagersInstructionDataCodec(): Codec<
  InitializeManagersInstructionDataArgs,
  InitializeManagersInstructionData
> {
  return combineCodec(
    getInitializeManagersInstructionDataEncoder(),
    getInitializeManagersInstructionDataDecoder(),
  );
}

export type InitializeManagersAsyncInput<
  TAccountVault extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  policyAccount?: Address<TAccountPolicyAccount>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  managers: InitializeManagersInstructionDataArgs["managers"];
};

export async function getInitializeManagersInstructionAsync<
  TAccountVault extends string,
  TAccountPolicyAccount extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS,
>(
  input: InitializeManagersAsyncInput<
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeManagersInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.policyAccount.value) {
    accounts.policyAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getAddressEncoder().encode(expectAddress(accounts.vault.value))],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeManagersInstructionDataEncoder().encode(
      args as InitializeManagersInstructionDataArgs,
    ),
    programAddress,
  } as InitializeManagersInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type InitializeManagersInput<
  TAccountVault extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  policyAccount: Address<TAccountPolicyAccount>;
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  managers: InitializeManagersInstructionDataArgs["managers"];
};

export function getInitializeManagersInstruction<
  TAccountVault extends string,
  TAccountPolicyAccount extends string,
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS,
>(
  input: InitializeManagersInput<
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeManagersInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountPolicyAccount,
  TAccountSigner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeManagersInstructionDataEncoder().encode(
      args as InitializeManagersInstructionDataArgs,
    ),
    programAddress,
  } as InitializeManagersInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountPolicyAccount,
    TAccountSigner,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeManagersInstruction<
  TProgram extends string = typeof POLICY_MANAGER_ACCESS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    policyAccount: TAccountMetas[1];
    signer: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeManagersInstructionData;
};

export function parseInitializeManagersInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeManagersInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      policyAccount: getNextAccount(),
      signer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeManagersInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
