/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from '../programs';

/** TransactionAlreadyExecuted: Transaction already executed. */
export const HYRO_PROTOCOL_ERROR__TRANSACTION_ALREADY_EXECUTED = 0x1770; // 6000
/** TransactionNotFound: Transaction not found. */
export const HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_FOUND = 0x1771; // 6001
/** TransactionNotExecutable: Transaction not executable. */
export const HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_EXECUTABLE = 0x1772; // 6002
/** InvalidUnderlyingMint: Invalid underlying mint. */
export const HYRO_PROTOCOL_ERROR__INVALID_UNDERLYING_MINT = 0x1773; // 6003
/** InvalidShareMint: Invalid share mint. */
export const HYRO_PROTOCOL_ERROR__INVALID_SHARE_MINT = 0x1774; // 6004

export type HyroProtocolError =
  | typeof HYRO_PROTOCOL_ERROR__INVALID_SHARE_MINT
  | typeof HYRO_PROTOCOL_ERROR__INVALID_UNDERLYING_MINT
  | typeof HYRO_PROTOCOL_ERROR__TRANSACTION_ALREADY_EXECUTED
  | typeof HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_EXECUTABLE
  | typeof HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_FOUND;

let hyroProtocolErrorMessages: Record<HyroProtocolError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  hyroProtocolErrorMessages = {
    [HYRO_PROTOCOL_ERROR__INVALID_SHARE_MINT]: `Invalid share mint.`,
    [HYRO_PROTOCOL_ERROR__INVALID_UNDERLYING_MINT]: `Invalid underlying mint.`,
    [HYRO_PROTOCOL_ERROR__TRANSACTION_ALREADY_EXECUTED]: `Transaction already executed.`,
    [HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_EXECUTABLE]: `Transaction not executable.`,
    [HYRO_PROTOCOL_ERROR__TRANSACTION_NOT_FOUND]: `Transaction not found.`,
  };
}

export function getHyroProtocolErrorMessage(code: HyroProtocolError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (hyroProtocolErrorMessages as Record<HyroProtocolError, string>)[
      code
    ];
  }

  return 'Error message not available in production bundles.';
}

export function isHyroProtocolError<
  TProgramErrorCode extends HyroProtocolError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    HYRO_PROTOCOL_PROGRAM_ADDRESS,
    code
  );
}
