/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { FEE_COLLECTION_FRACTIONS_PROGRAM_ADDRESS } from '../programs';

/** InvalidConfig: Invalid fee configuration */
export const FEE_COLLECTION_FRACTIONS_ERROR__INVALID_CONFIG = 0x1770; // 6000

export type FeeCollectionFractionsError =
  typeof FEE_COLLECTION_FRACTIONS_ERROR__INVALID_CONFIG;

let feeCollectionFractionsErrorMessages:
  | Record<FeeCollectionFractionsError, string>
  | undefined;
if (process.env.NODE_ENV !== 'production') {
  feeCollectionFractionsErrorMessages = {
    [FEE_COLLECTION_FRACTIONS_ERROR__INVALID_CONFIG]: `Invalid fee configuration`,
  };
}

export function getFeeCollectionFractionsErrorMessage(
  code: FeeCollectionFractionsError
): string {
  if (process.env.NODE_ENV !== 'production') {
    return (
      feeCollectionFractionsErrorMessages as Record<
        FeeCollectionFractionsError,
        string
      >
    )[code];
  }

  return 'Error message not available in production bundles.';
}

export function isFeeCollectionFractionsError<
  TProgramErrorCode extends FeeCollectionFractionsError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    FEE_COLLECTION_FRACTIONS_PROGRAM_ADDRESS,
    code
  );
}
