/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const OWNERS_DISCRIMINATOR = new Uint8Array([
  96, 145, 150, 191, 50, 61, 92, 51,
]);

export function getOwnersDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(OWNERS_DISCRIMINATOR);
}

export type Owners = {
  discriminator: ReadonlyUint8Array;
  owners: Array<Address>;
};

export type OwnersArgs = { owners: Array<Address> };

/** Gets the encoder for {@link OwnersArgs} account data. */
export function getOwnersEncoder(): Encoder<OwnersArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["owners", getArrayEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: OWNERS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Owners} account data. */
export function getOwnersDecoder(): Decoder<Owners> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["owners", getArrayDecoder(getAddressDecoder())],
  ]);
}

/** Gets the codec for {@link Owners} account data. */
export function getOwnersCodec(): Codec<OwnersArgs, Owners> {
  return combineCodec(getOwnersEncoder(), getOwnersDecoder());
}

export function decodeOwners<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Owners, TAddress>;
export function decodeOwners<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Owners, TAddress>;
export function decodeOwners<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Owners, TAddress> | MaybeAccount<Owners, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOwnersDecoder(),
  );
}

export async function fetchOwners<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Owners, TAddress>> {
  const maybeAccount = await fetchMaybeOwners(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOwners<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Owners, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOwners(maybeAccount);
}

export async function fetchAllOwners(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Owners>[]> {
  const maybeAccounts = await fetchAllMaybeOwners(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOwners(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Owners>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeOwners(maybeAccount));
}
