/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** Percentage-based fee configuration (basis points) */
export type FractionConfig = {
  /** LP fee in basis points (100 = 1%) */
  lpFeeBps: number;
  /** Manager fee in basis points */
  managerFeeBps: number;
  /** Protocol fee in basis points */
  protocolFeeBps: number;
  /** Performance fee in basis points (applied to profits above high water mark) */
  performanceFeeBps: number;
};

export type FractionConfigArgs = FractionConfig;

export function getFractionConfigEncoder(): FixedSizeEncoder<FractionConfigArgs> {
  return getStructEncoder([
    ["lpFeeBps", getU16Encoder()],
    ["managerFeeBps", getU16Encoder()],
    ["protocolFeeBps", getU16Encoder()],
    ["performanceFeeBps", getU16Encoder()],
  ]);
}

export function getFractionConfigDecoder(): FixedSizeDecoder<FractionConfig> {
  return getStructDecoder([
    ["lpFeeBps", getU16Decoder()],
    ["managerFeeBps", getU16Decoder()],
    ["protocolFeeBps", getU16Decoder()],
    ["performanceFeeBps", getU16Decoder()],
  ]);
}

export function getFractionConfigCodec(): FixedSizeCodec<
  FractionConfigArgs,
  FractionConfig
> {
  return combineCodec(getFractionConfigEncoder(), getFractionConfigDecoder());
}
