/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getDiscriminatedUnionDecoder,
  getDiscriminatedUnionEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getTupleDecoder,
  getTupleEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type GetDiscriminatedUnionVariant,
  type GetDiscriminatedUnionVariantContent,
} from '@solana/kit';

export type BalanceUpdate =
  | { __kind: 'NewValue'; fields: readonly [bigint] }
  | { __kind: 'Delta'; fields: readonly [bigint] };

export type BalanceUpdateArgs =
  | { __kind: 'NewValue'; fields: readonly [number | bigint] }
  | { __kind: 'Delta'; fields: readonly [number | bigint] };

export function getBalanceUpdateEncoder(): FixedSizeEncoder<BalanceUpdateArgs> {
  return getDiscriminatedUnionEncoder([
    [
      'NewValue',
      getStructEncoder([['fields', getTupleEncoder([getU64Encoder()])]]),
    ],
    [
      'Delta',
      getStructEncoder([['fields', getTupleEncoder([getI64Encoder()])]]),
    ],
  ]) as FixedSizeEncoder<BalanceUpdateArgs>;
}

export function getBalanceUpdateDecoder(): FixedSizeDecoder<BalanceUpdate> {
  return getDiscriminatedUnionDecoder([
    [
      'NewValue',
      getStructDecoder([['fields', getTupleDecoder([getU64Decoder()])]]),
    ],
    [
      'Delta',
      getStructDecoder([['fields', getTupleDecoder([getI64Decoder()])]]),
    ],
  ]) as FixedSizeDecoder<BalanceUpdate>;
}

export function getBalanceUpdateCodec(): FixedSizeCodec<
  BalanceUpdateArgs,
  BalanceUpdate
> {
  return combineCodec(getBalanceUpdateEncoder(), getBalanceUpdateDecoder());
}

// Data Enum Helpers.
export function balanceUpdate(
  kind: 'NewValue',
  data: GetDiscriminatedUnionVariantContent<
    BalanceUpdateArgs,
    '__kind',
    'NewValue'
  >['fields']
): GetDiscriminatedUnionVariant<BalanceUpdateArgs, '__kind', 'NewValue'>;
export function balanceUpdate(
  kind: 'Delta',
  data: GetDiscriminatedUnionVariantContent<
    BalanceUpdateArgs,
    '__kind',
    'Delta'
  >['fields']
): GetDiscriminatedUnionVariant<BalanceUpdateArgs, '__kind', 'Delta'>;
export function balanceUpdate<K extends BalanceUpdateArgs['__kind'], Data>(
  kind: K,
  data?: Data
) {
  return Array.isArray(data)
    ? { __kind: kind, fields: data }
    : { __kind: kind, ...(data ?? {}) };
}

export function isBalanceUpdate<K extends BalanceUpdate['__kind']>(
  kind: K,
  value: BalanceUpdate
): value is BalanceUpdate & { __kind: K } {
  return value.__kind === kind;
}
