/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum FeeCollectionFrequency {
  Monthly,
  Quarterly,
  Annually,
  OnWithdrawal,
}

export type FeeCollectionFrequencyArgs = FeeCollectionFrequency;

export function getFeeCollectionFrequencyEncoder(): FixedSizeEncoder<FeeCollectionFrequencyArgs> {
  return getEnumEncoder(FeeCollectionFrequency);
}

export function getFeeCollectionFrequencyDecoder(): FixedSizeDecoder<FeeCollectionFrequency> {
  return getEnumDecoder(FeeCollectionFrequency);
}

export function getFeeCollectionFrequencyCodec(): FixedSizeCodec<
  FeeCollectionFrequencyArgs,
  FeeCollectionFrequency
> {
  return combineCodec(
    getFeeCollectionFrequencyEncoder(),
    getFeeCollectionFrequencyDecoder(),
  );
}
