/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getFeeCollectionFrequencyDecoder,
  getFeeCollectionFrequencyEncoder,
  type FeeCollectionFrequency,
  type FeeCollectionFrequencyArgs,
} from ".";

export type ManagerFeeStructure = {
  performanceFeeRate: number;
  managementFeeRate: number;
  collectionFrequency: FeeCollectionFrequency;
  highWaterMark: bigint;
  feeRecipient: Address;
};

export type ManagerFeeStructureArgs = {
  performanceFeeRate: number;
  managementFeeRate: number;
  collectionFrequency: FeeCollectionFrequencyArgs;
  highWaterMark: number | bigint;
  feeRecipient: Address;
};

export function getManagerFeeStructureEncoder(): FixedSizeEncoder<ManagerFeeStructureArgs> {
  return getStructEncoder([
    ["performanceFeeRate", getU16Encoder()],
    ["managementFeeRate", getU16Encoder()],
    ["collectionFrequency", getFeeCollectionFrequencyEncoder()],
    ["highWaterMark", getU64Encoder()],
    ["feeRecipient", getAddressEncoder()],
  ]);
}

export function getManagerFeeStructureDecoder(): FixedSizeDecoder<ManagerFeeStructure> {
  return getStructDecoder([
    ["performanceFeeRate", getU16Decoder()],
    ["managementFeeRate", getU16Decoder()],
    ["collectionFrequency", getFeeCollectionFrequencyDecoder()],
    ["highWaterMark", getU64Decoder()],
    ["feeRecipient", getAddressDecoder()],
  ]);
}

export function getManagerFeeStructureCodec(): FixedSizeCodec<
  ManagerFeeStructureArgs,
  ManagerFeeStructure
> {
  return combineCodec(
    getManagerFeeStructureEncoder(),
    getManagerFeeStructureDecoder(),
  );
}
