/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum RiskRating {
  Conservative,
  Moderate,
  Aggressive,
  Speculative,
}

export type RiskRatingArgs = RiskRating;

export function getRiskRatingEncoder(): FixedSizeEncoder<RiskRatingArgs> {
  return getEnumEncoder(RiskRating);
}

export function getRiskRatingDecoder(): FixedSizeDecoder<RiskRating> {
  return getEnumDecoder(RiskRating);
}

export function getRiskRatingCodec(): FixedSizeCodec<
  RiskRatingArgs,
  RiskRating
> {
  return combineCodec(getRiskRatingEncoder(), getRiskRatingDecoder());
}
