/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS } from '../programs';

/** InvalidData: Invalid data. */
export const POLICY_LIMIT_TRANSFER_ERROR__INVALID_DATA = 0x1770; // 6000
/** AmountTooHigh: Amount too high. */
export const POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_HIGH = 0x1771; // 6001
/** AmountTooLow: Amount too low. */
export const POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_LOW = 0x1772; // 6002
/** InvalidSeed: Invalid seed. Non ASCII */
export const POLICY_LIMIT_TRANSFER_ERROR__INVALID_SEED = 0x1773; // 6003
/** InvalidPolicyPda: Invalid policy PDA. */
export const POLICY_LIMIT_TRANSFER_ERROR__INVALID_POLICY_PDA = 0x1774; // 6004

export type PolicyLimitTransferError =
  | typeof POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_HIGH
  | typeof POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_LOW
  | typeof POLICY_LIMIT_TRANSFER_ERROR__INVALID_DATA
  | typeof POLICY_LIMIT_TRANSFER_ERROR__INVALID_POLICY_PDA
  | typeof POLICY_LIMIT_TRANSFER_ERROR__INVALID_SEED;

let policyLimitTransferErrorMessages:
  | Record<PolicyLimitTransferError, string>
  | undefined;
if (process.env.NODE_ENV !== 'production') {
  policyLimitTransferErrorMessages = {
    [POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_HIGH]: `Amount too high.`,
    [POLICY_LIMIT_TRANSFER_ERROR__AMOUNT_TOO_LOW]: `Amount too low.`,
    [POLICY_LIMIT_TRANSFER_ERROR__INVALID_DATA]: `Invalid data.`,
    [POLICY_LIMIT_TRANSFER_ERROR__INVALID_POLICY_PDA]: `Invalid policy PDA.`,
    [POLICY_LIMIT_TRANSFER_ERROR__INVALID_SEED]: `Invalid seed. Non ASCII`,
  };
}

export function getPolicyLimitTransferErrorMessage(
  code: PolicyLimitTransferError
): string {
  if (process.env.NODE_ENV !== 'production') {
    return (
      policyLimitTransferErrorMessages as Record<
        PolicyLimitTransferError,
        string
      >
    )[code];
  }

  return 'Error message not available in production bundles.';
}

export function isPolicyLimitTransferError<
  TProgramErrorCode extends PolicyLimitTransferError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    POLICY_LIMIT_TRANSFER_PROGRAM_ADDRESS,
    code
  );
}
